# XX<br/>FINAL PARTICIPATION

I referred in Chapter XIII to symbolism as something in which we to-day are again becoming interested. There is no respect in which the imaginative literature and drama of to-day differs more strikingly from that of even fifty years ago. In those days there was an Ibsen, there was a Maeterlinck, but nobody really understood what they were up to and everyone was dubious and uncomfortable. Whereas to-day every other writer strives to imply some sort of symbolized content and, even if he does not, it is obligingly done for him by confident critics who have read their Freud and their Jung. It would be an interesting experiment to resuscitate a habitual reader of, say, the *Times Literary Supplement* in the ‘nineties, to set him down before the second half of the *New Statesman* in the 1950’s, and to see what he made of it.

In mentioning Freud and Jung I have, of course, touched on the most startling phenomenon of all. The unaccountable rapidity with which a literal-minded generation developed a sympathetic response to the psycho-analytical gnosis of dream-imagery, and accepted the (one would have thought) fantastic idea of an immaterial realm of ‘the unconscious’, is another sign, in addition to those I instanced in Chapter X, that the development of man’s consciousness is an evolutionary as well as a dialectical process. Who could possibly have foreseen it in the year of the Great Exhibition? Who could have failed to deny the possibility of such a change, if it had been foretold to him? Possibly the greatest, possibly the only lasting, value of psycho-analysis lies in its clinical aspect. It may or may not be so. But for the historian of consciousness the most significant thing will always be the way it ‘caught on’; the number of its technical terms—and still more the characters out of Greek mythology—which had become household words even before the death of its founder. Pan, it seems, has not only not retired from business; he has not only gone indoors; he has hardly shut the door, before we begin to hear him moving about inside.

Yet here again, as far as any extra-clinical value is concerned, the historian of the future will observe the fatally blighting influence of the conventional idolatry. It never seems to have even occurred to Freud that an individual man’s ‘unconscious mind’ could be anything but a ‘somewhat’ lodged inside the box of his bones. Representation, as a principle, is accepted by him as a matter of course; inasmuch as a great variety of dream-imagery is interpreted as symbolizing particular physical functions. From the perception that physical functions and organs are *themselves* representations, he is, however, cut off by all the assumptions of idolatry. Again, we have watched with interest Jung developing his concept of a ‘collective unconscious’ of humanity as a whole, a concept which is inherently repugnant to the foundation of idolatry on which he had to build it. Yet, because of that very idolatry, the traditional myths and the archetypes which he tells us are the representations of the collective unconscious, are assumed by him to be, and always to have been, neatly insulated from the world of nature with which, according to their own account, they were mingled or united.

The psychological interpretation of mythology is, it is true, a long way nearer to an understanding of participation than the old ‘personified causes’ of Tylor and Frazer and Lemprière’s Classical Dictionary. But it is still a long way off. In the last resort, when it actually comes up against the nature-content of the myths, it still relies on the old anthropological assumption of ‘projection’. I believe it will seem very strange to the historian of the future, that a liter-minded generation began to accept the actuality of a ‘collective unconscious’ before it could even admit the possibility of a ‘collective conscious’—in the shape of the phenomenal world.

I do not, however, think it can be very long now before this, too, is accepted; since it not only opens up possibilities of new knowledge of which the need is being increasingly felt, but also removes many inconsistencies in the contemporary picture of the world, which cannot fail to be noticed more and more as time passes. Idolatry carries in it the seeds of its own destruction. The reader will, for instance, recall the dilemma of ‘pre-history’ which was briefly touched on in Chapter V. We have chosen to form a picture, based very largely on modern physical science, of a phenomenal earth existing for millions of years before the appearance of consciousness. The same physical science tells us that the phenomenal world is correlative to consciousness. The phenomena attributed to those millions of years are therefore, in fact, abstract models or ‘idols of the study’. We may compromise by calling them ‘possible phenomena’, implying thereby that that was how the world would have looked, sounded, smelt and felt, *if* there had been someone like ourselves present. But if the only phenomena we know are collective representations, and what is represented is the collective unconscious, the awkward fact remains that it is highly fanciful, if not absurd, to think of any unperceived process in terms of potential phenomena, unless we also assume an unconscious, ready to light up into actual phenomena at any moment of the process.

This of course applies not only to pre-history, but to all the imperceptible process assumed in our picture of the contemporary world—the goings-on, for instance, at the bottom of the sea. But in the case of pre-history, we have further to remember that it does not suffice to accept the reality of a collective unconscious *now*. We have to accept that an unconscious, available to be represented, is at least coeval with any process describable in terms of phenomena. The employment of ‘models’ for the purpose of thinking may be very well; for the purposes of exposition it may even be essential—as long as we know what we are doing and do not turn the models into idols. And we shall know what we are doing with pre-history, when we have firmly grasped the fact that the phenomenal world arises from the relation between a conscious and an unconscious and that evolution is the story of the changes that relation has undergone and is undergoing.

But it is not only for the study of pre-history that it is all-important for us to realize this truth, that the phenomena are collective representations of what can *now* properly be called ‘man’s’ unconscious. It is vital for the future of the sciences. expecially those at the other end of the scale from the technological ones—those, in short, for which ‘dashboard-knowledge’ is not enough. When, for instance, we are dealing with living organisms, our whole approach, our whole possibility of grasping *process* as such, is hamstrung by the lack of just such a concept of the potentially phenomenal and the actually phenomenal.

With the help of the Arabian schoolmen the Aristotelian concept of ‘potential’ existence was gradually drained away into the mere notional ‘possibility’ of being—into *contingent* being. Thus, the word *potentialis* (itself a translation of the vigorous Greek word from which we take our ‘dynamic’ and ‘dynamite’) had been changed to *possibilis* before Aquinas wrote, though his *possibilis* still meant more than our ‘possible’. Since the scientific revolution, to ask whether a thing ‘is’ or ‘is not’ is, for science, to ask whether it is or is anot a phenomenon—either experienced or extrapolated. Francis Bacon, it will be remembered, found the distinction between *actus* and *potentia* ‘frigida distinctio’; and so it had to be, while the phenomena were becoming, and will be as long as they remain, idols. But to-day, it is no longer open to anyone who regards the unconscious as more than a fiction to contend that the concept of the potentially phenomenal, that is, of petential existence, is too difficult for human minds to grasp.

Even so, merely grasping the concept will not take mankind very far. Beta-thinking can go thus far. It can convince itself that, just as for original participation potential existence was something quite different from not-being, so, for the kind of participation at which we have arrived to-day, the potentially phenomenal is not the same as nothing. Let us call the man-centered participation with which the opening chapters of this book were concerned *final participation*. Beta-thinking, then, can convince itself of the *fact* of final participation. It can convince itself that we participate the phenomena with the unconscious part of ourselves. But that has no epistemological significance. It can only have that to the extent that final participation is consciously experienced. Perhaps (if we may already start using the old terminology which we have just taken out of the refrigerator) we may say that final participation must itself be raised from potentiality to act.

Are there any signs of such a development taking place? We have seen, in the Romantic movement, and elsewhere, symptoms of a kind of instinctive impulse towards iconoclasm. Are there any signs up to now of a *systematic* approach to final participation? And what does such an approach involve?

It was pointed out in Chapter XIII that participation as an actual experience is only to be won to-day by special exertion; that it is a matter, not of theorizing, but of imagination in the genial or creative sense. A systematic approach towards final participation may therefore be expected to be an attempt to use imagination systematically. This was the foundation of Goethe’s scientific work. In his book on the *Metamorphosis of Plants* and the associated writings descriptive of his method, as well as in the rest of his scientific work, there is the germ of a systematic investigation of phenomena by way of participation. For his *Urpflanze* and *Urphänomen* are nothing more or less than potential phenomena perceived and studied as such. They are processes grasped directly and not, as hitherto since the scientific revolution, hypotheses *inferred from* actual phenomena.

I have here used both the word ‘scientific’ and the word ‘perceived’ advisedly, though in such a context both of them run counter to all the assumptions of the received idolatry. It is a common objection that Goethe’s method ought not to be called ‘scientific’, because it was not purely empirical; but that objection obviously cannot be raised here without begging the whole argument of this book. As to ‘perceived’—we have seen that the major part of any perceived phenomenon consists of our own ‘figuration’. Therefore, as imagination reaches the point of enhancing figuration itself, hitherto unperceived parts of the whole field of the phenomenon necessarily become perceptible. Moreover, this conscious participation enhances perception not only of present phenomena but also of the memory-images derived from them. All this Goethe could not prevail on his contemporaries to admit. Idolatry was too all-powerful and there were then no premonitory signs, as there are to-day, of its collapse. No one, for instance, had heard of ‘the unconscious’.

For a student of the evolution of consciousness, it is particularly interesting that a man with the precise make-up of Goethe should have appeared at that precise moment in the history of the West. By the middle of the eighteenth century, when he was born, original participation had virtually faded out, and Goethe himself was a thoroughly modern man. Yet he showed from his earliest childhood and retained all through his life an almost atavistically strong remainder of it. It breathes through his poetry as the peculiar Goethean attitude to Nature, who is felt as a living being, almost as a personality, certainly as a ‘thou’ rather than as an ‘it’ or as an ‘I’. It is almost as if the Gods had purposely retained this sense in Goethe as a sort of seed-corn out of which the beginnings of final participation could peep, for the first time, on the world of science. Perhaps it was an instinctive understanding fo this which made him so determined to keep clear of beta-thinking.

>*Mein Kind, ich hab’es klug gemacht,<br/>Ich hab’ nie über das Denken gedacht.*¹

For beta-thinking leads to final, by way of the inexorable elimination of all original, participation. Consequently Goethe was able to develop an elementary technique, but unable, or unwilling, to erect a metaphysic, of final participation. The contrast in this respect between him and Schiller, who knew his Kant and stood firm in the idolatry of his contemporaries—especially as it appeared in a certain conversation² between the two on the subject of the *Urphänomen*—is illuminating and is in a manner, as I have said, analogous to the contrast between Wordsworth and Coleridge. There is, so far as I know, more of the historical *theory* of participation in Schiller’s poem *Die Götter Griechenlands* (from which I have already quoted in Chapter XIX) than in anything Goethe ever wrote. Yet Schiller could not admit the practical possibility of final participation at all. He told Goethe that his *Urphänomen* was no more than an idea, a hypothesis; and the poem itself, after a magnificent account of the retreat of the Gods from nature into man, has nothing more significant or prophetic to conclude with than the rather trite:

>*Was unsterblich im Gesang soll leben<br/>Muss im Leben untergehen*.³

The significance of Goethe in the history of science will be appreciated, as time passes, in the measure that idolatry is overcome. His theory of colour, for instance, will always be heterodox as long as the phenomenon of light is simply identified with the unrepresented ‘particles’. But that significance, however great it may ultimately appear, grows pale before the significance of Rudolf Steiner (1861-1925) who, in the early part of his life, studied and developed the method of Goethe. Unlike Goethe, however, Steiner did not avoid beta-thinking. At the same time that he was editing Goethe’s scientific works in Weimar, he was writing his book *The Philosophy of Spiritual Activity*, in which the metaphysic of final participation is fully and lucidly set forth. Educated on ‘the modern side’ (as we should then have said) at school and university, he was thoroughly at home with the idols and never relied on any relic of original participation there may have been in his composition to overcome them. It is in his work and that of his followers that the reader should look for further signs of a development towards final participation in the field of science.

If a single example is sought, let it be the research now going on in the domain of cancer. Cancer is a process of generation, and once we admit the concept of the potentially phenomenal, we must see that generation is not a transition from not-being to being, but a transition from potential to phenomenal existence. Steiner’s method, based on perception of the potentially phenomenal, was to diagnose a pre-cancerous condition of the blood, a condition not yet detectable by physical symptoms, and thus to take the disease at a stage where it answers better to treatment. This is another way of saying that the method involves investigation of a part of the field of the whole phenomenon named *blood* which, for a non-participating consciousness, is excluded from it, not by empirical proof but rather (as we saw in Chapter XII) by definition. He sought to apply the same method to the discovery of remedies, and The Society for Cancer Research founded by his followers is patiently continuing this difficult work at Arlesheim in Switzerland. At the moment in which I am writing, however, more people are probably acquainted with the ‘Biodynamic’ method in Agriculture than with the particular example I have chosen.

The mind of Rudolf Steiner was of course not only applied to the scientific sphere, and it was perhaps not even the most important part of his work. He is, for instance, far more illuminating and, I would say, reliable on the subject of language and its origin than Fabre d’Oliver and the others I mentioned in Chapter XVIII. To say that he advocated, and practised, ‘the systematic use of imagination’ is to place so much emphasis on the mere beginning of what he taught and did, that it is rather like saying that Dante wrote a poem about a greyhound. Steiner showed that imagination, and the final participation it leads to, involve, unlike hypothetical thinking, the whole man—thought, feeling, will, and character—and his own revelations were clearly drawn from those further stages of participation—Inspiration and Intuition—to which the systematic use of imagination may lead. Although the object with which this book was originally conceived was none other than to try to remove one of the principal obstacles to contemporary appreciation of precisely this man’s teaching—the study and use of which I believe to be crucial for the future of mankind—I shall here say no more of it. This is a study in idolatry, not a study of Rudolf Steiner.⁴

>¹ “I have managed things cleverly, my boy: I have never thought about thinking.’ *Zahme Xenien*, vi.

>² *Naturwissenschaftliche Schriften (Kürschner-Ausgabe)*. Vol. i, p. 109; Appendices to the *Metamorphosenlehre (Glückliches Ereignis)*.

>³ ‘What is to live immortal in song must go under in life.’

>⁴ All the published works of Rudolf Steiner are obtainable in London, either in English translation or in the original German, from:<br/>Rudolf Steiner Book Shop, 35 Park Road, N.W.I. or Rudolf Steiner Book Centre, 54 Bloomsbury St., W.C.I.
