# XIV<br/>BEFORE AND AFTER THE SCIENTIFIC REVOLUTION

For medieval man, then, the universe was a kind of theophany, in which he participated at different levels, in being, in thinking, in speaking or naming, and in knowing. And then—the evolutionary change began. Not, of course, at any given moment, but with anticipations, localized delays, individual differences. But no beginning is instantaneous—otherwise the very word ‘begin’ would be unnecessary and indeed meaningless. We need not pay too much attention to those historians who cautiously refuse to detect any process in history, because it is difficult to divide into periods, or because the periods are difficult to date precisely. The same objections apply to the process of growth from child to man. We should rather remind them that, if there is no process, there is in fact no such thing as history at all, so that they themselves must be regarded as mere chroniclers and antiquarians—a limitation which I cannot fancy they would relish. Moreover, the mental image, which they transfer to history, of a formless process determined by the chance impact of events, is itself, as we saw in Chapter IX, a product of the idolatry of the age of literalness.

However this may be, and whatever chronological limits we choose to assign to it, a change there certainly was. Professor Butterfield has commented well on it:

>through changes in the habitual use of words, certain things in the natural philosophy of Aristotle had now acquired a coarsened meaning or were actually misunderstood. It may not be easy to say why such a thing should have happened, but man unconsciously betray the fact that a certain Aristotelian thesis simply has no meaning for them any longer—they just cannot think of the stars and heavenly bodies as things without weight even when the books tell them to do so. Francis Bacon seems unable to say anything except that it is obvious that these heavenly bodies have weight, like any other kind of matter which we meet in our experience. Bacon says, furthermore, that he is unable to imagine the planets as nailed to crystalline spheres; and the whole idea only seems more absurd to him if the spheres in quetstion are supposed to be made of that liquid, aetherial kind of substance which Aristotle had in mind. Between the idea of a stone aspiring to reach its natural place at the centre of the universe—and rushing more fervently at it came nearer home—and the idea of a stone accelerating its descent under the constant force of gravity, there is an intellectual transition which involves a change in men’s feeling for matter.¹

We have seen that this change in men’s feeling for matter is merely one aspect of a much deeper and more fundamental change. And the change in men’s feeling for the nature of words and of thought was no whit less marked. Thus, the polarity of *actus* and *potentia* had carried perhaps half the weight of the philosophical thought of the Western mind through all the centuries that elapsed between Aristotle and Aquinas. A medieval philosopher would not have put the argument as I was obliged to do, when I said in Chapter III that there is ‘no such thing’ as unfelt solidity, just as there is no such thing as an unseen rainbow. He would have said that both the unsesn rainbow and the unfelt matter are *in potentia*. Yet this polarity, taken for granted for more than a thousand years by some of the acutest intellects the world has ever known—this polarity has become, for Bacon, a ‘frigida distinctio’—mere words! Again, in the *Novum Organum* he tells men bluntly that they ought not to think of ‘forms’ any more. They are really more like ‘laws’.

>It may be that nothing really exists except individual bodies, which produce real motion according to law; in science it is just that law, and the inquiry, discovery and explanation of it, which are the fundamental requisite both for the knowledge and for the control of Nature. And it is that law and its ‘clauses’, which *I* mean when I use (chiefly because of its current prevalence and familiarity) the word ‘forms’.²

*Causa exemplaris* is gone, in other words, and mechanical causality and the idols are already in sight.

If, with the help of some time-machine working in reverse, a man of the Middle Ages could be suddenly transported into the skin of a man of the twentieth century, seeing through our eyes and with our ‘figuration’ the objects we see, I think he would feel like a child who look for the first time at a photograph through the ingenious magic of a stereoscope. ‘Oh!”, he would say, ‘look how they *stend out!*’ We must not forget that in his time perspective had not yet been discovered, nor underrate the significance of this. True, it is no more than a device for pictorially representing depth, and separateness, in space. But how comes it that the device had never been discovered before—or, if discovered, never adopted? There were plenty of skilled artists, and they would certainly have hit upon it soon enough if depth in space had characterized the collective representations they wish to reproduce, as it characterizes ours. They did not need it. Before the scientific revolution the world was more like a garment men wore about them than a stage on which they moved. In such a world the convention of perspective was unnecessary. To such a world other conventions of visual reproduction, such as the nimbus and the halo, were as appropriate as to ours they are not. It was as if the observers were themselves *in* the picture. Compared with us, they felt themselves and the objects around them and the words that expressed those objects, immersed together in something like a clear lake of—what shall we say?—of ‘meaning’, if you choose. It seems the most adequate word. Aquinas’s *verbum intellectus* was *tanquam speculum, in quo res cernitur*³—’like a mirror in which the object is discerned’.

It happened that, at a time when I was studying the *De Natura Verbi Intellectus*, with that peculiar mixture of perplexity and delight which Thomas’s sentences arouse, when his thinking is at its intensest and tersest, I had the good fortune to receive from a friend the gift of a volume of his own poems. It seemed to me then, and it still seems to me now, that in one of them he has managed, without setting out to do so, to convey more vividly than I could ever hope to do, the qualitative difference between a participating outlook on the world, and our own. I therefore conclude my chapter with it.

>REFLECTION

>*When hill, tree, cloud, those shadowy forms<br/>Ascending heaven are seen,<br/>Their mindless beauty I from far<br/>Admire, a gulf between;*

>*Yet in the untroubled river when<br/>Their true ideas I find,<br/>That river, joined in trance with me,<br/>Becomes my second mind.*⁴

>¹ *Origins of Modern Science*, p. 104.

>² *Novum Organum*, II, 2. Author’s translation.

>³ *De Natura Verbi Intellectus*.

>⁴ George Rostrevor Hamilton. *The Carved Stone*. Heinemann. 1952.
