# V<br/>PRE-HISTORY

A history of the ‘world’, as distinct from a history of the unrepresented, must clearly be a history of phenomena; that is, of collective representation. But before this part of the subject is approached, it will be well to consider briefly the bearing of this truth on what is sometimes called pre-history. I mean, in particular, the history of the earth before the appearance on it of human beings.

When particles of rain, rays of light and our watching eyes are appropriately disposed, we see a rainbow. In the same way, given the existence of the particles and the presence of human beings on the earth, there arise collective representations, or in other words the phenomena which we call ‘nature’. When dealing with times in which these conditions were present, therefore, it is quite reasonable to describe and investigate nature scientifically, not only in the manner of physics, but also in the manner of the sciences whose field of study is the past as well as the present, such as geology, ecology, zoology, and to do this *as if* the phenomena were wholly independent of man’s sensory and psychological participation. It is not necessarily misleading to do so, and it has proved to be of great practical use. It is however not sufficiently realized that different considerations apply to nay description, in familiar terms, of natural events and processes deemed to have taken place before the appearance of human life on the earth.

It may of course be contended (though I should not like the task) that some animals enjoy representations sufficiently coherent to set up a phenomenal whole, which could be called ‘a world’ or ‘nature’. But this does not really assist much. For, although animals appeared on earth before man, it is certainly not *their* world or nature which geology, for instance, describes; and even so there remains the whole vast panorama of pre-hostory which is assumed to have preceded the emergence on this planet of sentient life of any description.

Yet by combining, say, biology and geology and omitting physics and physiology, such descriptions are continually offered to us and form, I suppose, a recognized part of the education of most children to-day. It can do no harm to recall occasionally that the prehistoric evolution of the earth, as it is described for example in the early chapters of H. G. Wells’s *Outline of History*, was not merely never seen. It never occurred. Something no doubt occurred, and what is really being propounded by such popular writers, and, so far as I am aware, by the text-books on which they rely, is this. That at that time the unrepresented was behaving in such a way that, *if* human beings with the collective representations characteristic of the last few centuries of western civilization had been there, the things described whould also have been there.

This is not quite the same thing. It needs, I should have thought, to be considered in connection with another fact, namely, that wehn attention is *expressly* directed to the history of the unrepresented (as in calculations of the age of the earth based on radio-activity), it is invariably assumed that the behaviour of the unrepresented has remained fundamentally unchanged. Moreover (and this is, to my mind, more important), for those hypothetical ‘human beings with collective representations characteristic of the last few centuries of western civilization’ we might choose to substitute other human beings—those, for instance, who lived one or two or three or more thousand years ago. We should then have to write a different pre-history altogether. And we are not entitled to assume without inquiry that, as an indirect means of suggesting the truth about pre-historic boings-on in the unrepresented, such an alternative ‘model’ would be any less efficient than the one we have in fact chosen. It might be very much more so.

As these consequences may be startling enough to the reader to cause him to reject them, even though he has so far followed me with tympathy, I will, at the risk of repeating myself, put as clearly as I can the alternatives to accepting them. If we refuse to accept them, we can adopt one of three courses, to each of which there are, to me, insuperable objections. We can adopt a sort of super-na&#238;ve realism, rejecting all the rigmarole of physics, physiology and psychology with the healthy instinct of Dr. Johnson kicking his stone. ‘Nature is nature, and the earth is the earth, and always has been since it all began.’ This may do for the present moment, but for a scientifically reconstructed prehistoric past it is open to the objection that, if we are going to reject the reasoned inferences of one set of scientists, there seems no particular reason why we should accept those of another. Or we can resort frankly to ‘double-think’. We can think that what physics tells us is true, is true when we are studying physics, and untrue when we are studying something else. The objections to this course are obvious to me, and will be equally so to some of my readers. There are those who will nevertheless continue to adopt it. This book is addressed to the others. Lastly we can adopt a Berkeleyan view of phenomena. For Berkeley held that, not merely the unrepresented, but the representations *as such*, are sustained by God in the absence of human beings. This involves the, for me, too difficult corollary that, out of all the wide variety of collective representations which are found even to-day over the face of the earth, and the still wider variety which history unrolls before us, God has chosen for His delight the particular set shared by Western man in the last few centuries.

It does not of course necessarily follow that all the current descriptions of pre-history are absurd. Even if the usual way of recording what, in the absence of man, was going on in the unrepresented must be criticised as a dubious extrapolation, the descriptions may still, as I have suggested, but valuable, not as actual descriptions, but as notional ‘models’. What is important is, to remember that that is all they are. (Especially will this be the case, if we should ever have to assess the merits of this approach against those of any other possible way of acquiring knowledge of the pre-historic past.) For  their nature is that of artificial imagery. And when the nature and limitations of artificial images are forgotten, they become idols. Francis Bacon declared that the medieval approach to reality was under the spell of four different sorts of idols, which he called ‘idols of the cave’, ‘idols of the tribe’ and so forth. In the same way, these images of what was going on in the unrepresented in the pre-historic past may be called ‘idols of the study’. At least that is what they are, if their nature and limitations are forgotten. And I am not sure that as yet these have even been *noticed*.

It is, however, not only these purely theoretical or academic idols with which this book is concerned.
