# XVIII<br/>THE ORIGIN OF LANGUAGE

We have seen that, in the older doctrine of invented and applied ‘roots of speech’, as pointing to the origin of language, and in the more recent one of ‘metaphor’ as the principal instrument of the growth of meaning, we are saddled with two notions, which are both of them inconsistent with the testimony of language itself. If, on the other hand, we approach the history of meaning free from all assumptions based on biological theories of evolution; if we take our stand simply on a faithful study of the *nature* of language, then we shall not be seduced into any such arbitrary surmises. Instead, we shall be obliged to admit that ‘metaphor’ is a misleading concept to apply to any but the later and more sophistocated stages of language. For all the evidence points rather to that sort of ‘polarization’ of an ancient unity into an outer and an inner meaning, which was traced in Chapter XII. In other words, it points to the source of language in original participation—and, in doing so, indicates the direction in which we must look for a true understanding of those mysterious ‘roots’. It is there, too, that we may hope in the end to espy the historical function of the word in determining the relation between thought and things.

We have seen that the difference between what I have called ‘original’ participation and the participation which can be grasped to-day in beta-thinking is, above all, a difference of direction. In the former, the represented is felt to be on the other side of the phenomena from the perceiving self. At the same time, it is felt to be linked with, or related to, that self otherwise than through the senses. The self, so far as there yet is one, is still aware that it and the phenomena derive from the same supersensible source. The kind of consciousness, then, is the subjective aspect that coming-into-being, *pari passu*, of man and of his phenomena, which was referred to in Chapter X. Objectively, we could only describe the earlier stages of this process as a time when man—not only as a body, but also as a soul—was a part of nature in a way which we to-day, of course, find it difficult to conceive. Subjectively, he could not yet ‘call his soul his own’. The farther back we penetrate, the more indistinguishable would his acts and utterances become from processes taking place in what has since become ‘outer’ nature.

It is conditions such as these which we must strive to realize in imagination, if we would hope to understand the ‘root’ element in language. Speech did not arise as the attempt of man to imitate, to master or to explain ‘nature’; for speech and nature came into being along with one another. Strictly speaking, only idolators can raise the question of the ‘origin of language’. For anyone else to do so is like asking for the origin of origin. Roots are the echo of natrue herself sounding in man. Or rather, they are the echo of what once sounded and fashioned in both of them at the same time. And therefore it is, that they have always fascinated those adventurous sould—such as Fabre d’Olivet, Court do Gébelin or, in our own time, Herman Beckj, A.D. Wadler and others—who have sought to explore that difficult and perplexing territory—devastated as it has been by ensuing millennia of cultural divergence and etymological accidents—the relation between the sounds of language and its meanings.

The split between sound and meaning—for their relation in any modern language is no more than vestigial—is one aspect of the ever-widening gulf between outer and inner, phenomenon and name, thing and thought, with which this book is concerned. We have seen how that polarization into man:nature, which was the means to man’s self-consciousness, was exaggerated by the scientific revolution into an exclusive disjunction. It was still a polarity, so long as *some* image-consciousness, *some* participation survived. We have seen also, in the preceding chapter, how the disjunction was deliberately purposed by the Jewish nation. I believe it will some day be realized that their mission was at the same time to prepare humanity against the day when it should be complete—that is, our own time.

The Hebrew language, through which (as we have seen) the inwardness of the Divine Name was later revealed, is at the same time, according to some opinions, that one among the ancient languages in which the roots preserve most clearly (although still dimly enough) the old unity of sound and meaning. If we try to think of these roots as ‘words’, then we must think of words with a potential rather than an actual meaning. Certainly those who have any feeling for sound-symbolism, and who wish to develop it, will be well advised to ponder them. They may find, in the consonantal element in language, vestiges of those forces which brought into being the external structure of nature, including the body of man; and, in the original vowel-sounds, the expression of that inner life of feeling and memory which constitutes his soul. It is the two together which have made possible, by first physically and then verbally embodying it, his personal intelligence.

The objective of this book is, however, a limited one, namely, to demonstrate on general grounds the necessity of smashing the idols. It cannot, therefore, attempt to investigate in detail what sort of knowledge may result from doing so, and it would be quite beyond its scope to carry this difficult subject any further. Suffice it to say that the Semitic lnaguages seem to point us back to the old unity of man and nature, through the shapes of their sounds. We feel those shapes not only as sounds, but also, in a manner, as *gestures* of the speech-organs—and it is not so difficult to realize that these gestures were once gestures made with the whole body—once—when the body itself was not detached from the rest of nature after the solid manner of to-day, when the body itself was spoken even while it was speaking.

In an Aryan language, such as Greek, on the other hand, where natural and mythological significances so easily meet and mingle, we can feel more easily the nature of *phenomenal*—that is, imaginal—participation. The Aryan tongues point to the same ancient unity as the Semitic—but they do so through the quality of their *meaning*. Among the speakers of both types of language, a few centuries before the Christian era, a last faint echo of that unity appeared in the form of tradition and doctrine.

In the *Sefer Yezirah*, for instance, whose authorship was traditionally assigned to Abraham, and which was perhaps first committed to writing about B.C. 600, the account of creation given in the Book of Genesis is expanded, and related in considerable detail to the sounds and signs of a language at once divine and human. And the influence of the Jewish doctrine of the Word of God, which was at the same time the source of the phenomenal world and the incarnation of wisdom in man, is still clearly apparent in the Book of Proverbs and in the apocryphal *Ecclesiasticus* and *Wisdom of Solomon*. In the world of Greek thought the development in a similar direction, and particularly by the Stoic sect, of the *logos* of the Greek philosophers is better known; and it is an old story how the two streams met in Alexandria and united in the form which is probably best exemplified in the writings of Philo Judaeus.

All things came into being through the Word. This teaching of the creative Word, this last testimony to a creation which was not a mere creation of idols, and to an evolution which was not a mere evolution of idols, is one which Christian thought, thanks to the opening verses of St. John’s Gospel, has never been able entirely to ignore, though it has by now come near to doing so. But the significance of this must be deferred to a later chapter.
