# XI<br/>MEDIEVAL ENVIRONMENT

When the distinction has been appreciated between (1) an imputed evolution of some wholly ‘objective’, and therefore wholly unrepresented base, (2) a fancied evolution of idols, and (3) the actual evolution of phenomena (including, as that does, a correlative evolution of consciousness), we may be compelled to revise some of our ideas on the amount of time required for the process. It follows, for instance, from what was said in Chapter V, that the period during which the *phenomenal* earth has been evolving is probably much shorter than is now generally assumed. Another consequence is, that evolutionary changes are not purely biological, and that they are not limited to pre-history, but can be detected even in the relatively recent period for which historical records, or indications of some sort, are still available to us. They include changes subtler in their nature and observable over a different time-scale altogether, changes measurable by centuries rather than millennia, and by millennia rather than aeons.

It has already been suggested that the last of these changes occupied only the three or four hundred years which divide our own epoch from the one which preceded the scientific revolution. For this suggestion was implied throughout, in the attempt which was made in Chapter VI and VII to trace the coming into being of our own collective representations. It is now the task of this book to demonstrate in rather more detail, if that be possible, that the men of the middle ages, and their predecessors, did indeed live in a different world from ours. The difficulties in the way of such a demonstration are very great, because, as I have pointed out, it is the very nature of our own representations that they are fixed, as a sort of idols to which all representative significance is denied, and which cannot therefore (so it is felt) have altered merely with the alteration of human consciousness. Since it is, for us, a matter of ‘common sense’, if not of definition, that phenomena are wholly independent of consciousness, the impulse to ignore or explain away any evidence to the contrary is almost irresistable.

Yet, as with most inveterate prejudices, the reward of overcoming it requites the exertion. The idols are tough and hard to crack, but through the first real fissure we make in them we find ourselves looking, how deeply, into a new world! If the eighteenth-century botanist, looking for the first time through the old idols of Linnaeus’s fixed and timeless classification into the new perspective of biological evolution, felt a sense of liberation and light, it can have been but a candle-flame compared with the first glimpse we now get of the familiar world and human history lying together, bathed in the light of the evolution of consciousness.

That, in a colloquial or metaphorical sense, the man of the middle ages lived in ‘a different world’ from ours, is obvious enough from the record. Half an hour spent with the illuminated manuscripts in the British Museum would be enough to convince anyone of this, even if there were no cathedrals, no Mystery plays, no frescoes, no heraldry, no psychomachies, no Virgil legend, no Divine Comedy still surviving. But we have here not merely to notice the fact that medieval man expressed himself in so different a manner and in such different terms from those which are natural to us, but to ask the question *why* he did so. Besides producing representations in perception and memory, men reproduce them in their language and are; it is, indeed, in this way that the representations become collective. Through language and traditional art we come without effort to share in the collective representations of our own age and our own community. But where we are concerned with those of an alien or a vanished community, we cannot bring ourselves to the point of sharing them without making an unwonted effort. We have to try to experience them as vitally *as if* they were ours—but our own keep on getting in the way.

The first obvious impression which the art and literature of the Middle Ages make upon us is one of ‘quaintness’—that quaintness which disgusted the eighteenth and fascinated the nineteenth century. If we go farther and ask in what this quaintness consists, I think we shall find that it arises, above all, from their combining and, as we should say, confusing two ways of approaching phenomena; ways which we are accustomed to regard as quite distinct from one another. These are the literal, on the one hand, and the symbolic or metaphorical, on the other. In their art, for instance, they felt none of the awkwardness we do about representing invisible or spiritual events and circumstances by material means. The same human figures, costumes, artefacts, etc., could be used in the same picture or carving as literal reproductions of the physical world and as representations of a spiritual world. A farm cart would do for Elijah’s fiery chariot on its way up to heaven—and look at any fresco of the Last Judgment.

In the eighteenth and nineteenth centuries men who wanted to paint or sculpt an angel, for instance, or a departed spirit, felt obliged to supply him with a special, unearthly costume—often rather like a nightgown. But *then* there seemed nothing incongruous in using the garments of every day. Certainly, in both periods, angels were often represented with wings, but this really only emphasizes the difference—for they would add wings to the ordinary human figure ordinarily attired, whereas it would clearly be aesthetically impossible and theologically a joke in bad taste to attach wings to a lounge suit. It may be suggested that there is a very simple explanation, namely that lounge suits are ‘prosaic’, whereas armour, tabards and hose are not. But this is no explanation at all, unless we can also say what we mean by ‘prosaic’, and therefore *why* our clothes are prosaic, whereas medieval clothes were not. If we cannot, then we are merely left with another form of the same statement. A prosaic object, in other words, is a non-representational one; and our clothes are prosaic, because our minds are literal.

It is very important to realize that, when it is said that the man of medieval and earlier times confused the literal and symbolical approach, what is meant is, that he confused or rather combined the two states of mind *which we to-day mean by those words*. Indeed, we shall find throughout that the main difficulty that prevents us from breaking through the idols to the actuality of history, that is, to the evolution of consciousness, lies in the fact that we go on using the same words without realizing how their meanings have shifted. Thus, exceptional men did sometimes distinguish between the literal and the symbolical use of words and images before the scientific revolution. On the question of hell, for instance, John Scotus Erigena distinguished in the ninth century between the symbol and the symbolized or the representation and the represented , emphasizing that the sufferings of hell are purely spiritual, and that they are described physically for the benefit of simple understandings. The point I am making is that, precisely to those simple understandings, the ‘physical’ and ‘literal’ themselves were not what ‘physical’ and ‘literal’ are to us. Rather, the phenomena themselves carried the sort of multiple significance which we to-day only find in symbols. Accordingly, the issue, in a given case, between a literal and a symbolical interpretation, though it could be raised, had not the same sharpness as of contradictories. Later, as the representations hardened into idols, the distinction between the two grew sharper and sharper until, in the nineteenth century, the strain of a ‘literal’ interpretation became intolerable even to simple understandings, and the notion of, for instance, a ‘physical’ hell was decisively rejected as an impossible superstition. And so indeed it is, if by ‘physical’ we mean the idols of which our physical world to-day consists. ‘Who now believes,’ inquired F. C. Conybeare in 1910, ‘in a God who has a right and a left hand?’¹

When the ‘things’ of the physical world have become idols, then indeed the literal interpretation excludes the symbolical, and *vice versa*. But where every thing is a representation, at least half-consciously experienced as such, there is as yet no such contradiction. For a representation experienced as such is neither literal nor symbolical; or, alternatively, it is both at the same time. Nothing is easier for us, than to grasp a purely literal meaning; and if we are capable at all of grasping, in addition, a symbolical or ‘fancy’ meaning, as we do in poetry, we are in no danger of confusing the one with the other.² Before the scientific revolution, on the other hand, it was the concept of the ‘merely literal’ that was difficult. And therefore the writer who is referred to as Dionysius the Areopagite, and Thomas Aquinas and others after him, emphasized the importance of using the humblest and most banal images, as symbols for purely spiritual truths or beings. For only in this way could a representation be safely polarized into symbol and symbolized, into literal and metaphorical.

We have seen that phenomena are experienced collectively *as* representations, and not as idols, where there is a survival of participation. In attempting to show that, right down to the period which ended with the scientific revolution, there was such a survival, I can do no more than give a few selected indications. The reader must go elsewhere for a full and detailed account of the medieval outlook.

Since participation is a *way* of experiencing the world in immediacy, and not a system of ideas about experience, or about the world, we obviously shall not find any contemporary *description* of it. When we come to contemporary philosophy and theories of knowledge, we shall indeed find explicit *references* to participation, but for the moment we are concerned with the ordinary man’s experience and not with what philosophers thought about that experience. Contemporary books were written, and contemporary science was expounded, for people assumed to share the collective representations of the writer, and accordingly our evidence must be sought more often in what is implied or assumed than in what is actually affirmed. We can only reconstruct the collective representations of another age obliquely.

Let us make the attempt for a moment. Let us try to place ourselves inside the skin of a medieval ‘man in the street’, and imagine ourselves looking out at the world through his eyes and thinking about it—not speculating, but thinking ordinary habitual thoughts—with his mind. We are not concerned with what he believed as an obligation of faith or a point of doctrine remote from experience. We are concerned with the sort of thing he took for granted.

To begin with, we will look at the sky. We do not see it as empty space, for we know very well that a vacuum is something that nature does not allow, any more than she allows bodies to fall upwards. If it is daytime, we see the air filled with light proceeding from a living sun, rather as our own flesh is filled with blood proceeding from a living heart. If it is night-time, we do not merely see a plain, homogeneous vault pricked with separate points of light, but a regional, qualitative sky, from which first of all the different sections of the great zodiacal belt, and secondly the planets and the moon (each of which is embedded in its own revolving crystal sphere) are raying down their complex influences upon the earth, its metals, its plants, its animals and its men and women, including ourselves. We take it for granted that those invisible spheres are giving forth an inaudible music—the spheres, not the individual stars (as Shakespeare’s Lorenzon instructed Jessica, much later, when the representation had already begun to turn into a vague superstition). As to the planets themselves, without being specially interested in astrology, we know very well that growing things are specially beholden to the moon, that gold and silver draw their virtue from sun and moon respectively, copper from Venus, iron from Mars, lead from Saturn. And that our own health and temperament are joined by invisible threads to those heavenly bodies we are looking at. We probably do not spend any time thinking about these extra-sensory links between ourselves and the phenomena. We merely take them for granted.

We turn our eyes to the sea—and at once we are aware that we are looking at one of the four elements, of which all things on earth are composed, including our own bodies. We take it for granted that these elements have invisible constituents, for, as to that part of them which is incorporated in our own bodies, we experience them inwardly as the four ‘humours’ which go to make up our temperament. (To-day we still catch the lingering echo of this participation, when Shakespeare makes Mark Antony say of Brutus:

>*. . . The elements<br/>So mixed in him, that Nature might stand up<br/>And say to all the world, This was a man.*)

Earth, Water, Air and Fire are part of ourselves, and we of them. And through them also the stars are linked with our inner being, for each constellated Sign of the Zodiac is specially related to one of the four elements, and each element therefore to three Signs.

A stone falls to the ground—we see it seeking the centre of the earth, moved by something much more like desire than what we to-day call gravity. We prick our finger and a drop of red blood appears. We look at the blood . . . but for the moment I will not pursue this any further. The reader who is at all acquainted with the productions of the medieval mind, its alchemy, its medicine, its herb-lore, its bestiaries, and so forth, can do it better for himself. For the reader who is not so acquainted there are the libraries—better still, there are those inexhaustible encyclopedias in stone, the cathedral carvings.

Whatever their religious or philosophical beliefs, men of the same community in the same period share a certain background-picture of the world and their relation to it. In our own age—whether we believe our consciousness to be a soul ensconced in a body, like a ghost in a machine, or some inextricable psychosomatic mixture—when we think *casually*, we think of that consciousness as situated at some point in space, which has no special relation to the universe as a whole, and is certainly nowhere near its centre. Even those who achieve the intellectual contortionism of denying that there is such a thing as consciousness, feel that this denial comes from inside their own skins. Whatever it is that we ought to call our ‘selves’, our bones carry it about like porters. This was not the background picture before the scientific revolution. The background picture then was of man as a microcosm within the macrocosm. It is clear that he did not feel himself isolated by his skin from the world outside him to quite the same extent as we do. He was integrated or mortised into it, each different part of him being united to a different part of it by some invisible thread. In his relation to his environment, the man of the middle ages was rather less like an island, rather more like an embryo, than we are.

>¹*Myth, Magic and Morals*.

>²The meaning, for instance, of the word *garden* in the line: *There is a garden in her face*, is unlikely to be mistaken for the literal meaning.
