# VIII<br/>TECHNOLOGY AND TRUTH

We have just distinguished between the actual doctrines of modern science and the collective representation to which the growth of science has contributed. Thus, on the one hand attention may be directed to the history of alpha-thinking itself—what is ordinarily called the history of thought or the history of ideas. On the other hand it may be turned to the *effects* of an alpha-thinking which has continued long and widely enough to pass over into figuration, and be, as it were, smitten into the representations themselves; that is part of the history of *consciousness*, and of the collective representations which are its correlative. Now although my subject is not the doctrines of science, but rather the collective representations, which have been so deeply affected by the doctrines of science, it may be well to pause here for a moment and consider the relation of scientific theories to truth and knowledge.

What is the view taken by scientists themselves of that relation? The answer is not very clear. And it is a good deal less clear to-day than it was a generation ago. The limited scope of all scientific inquiry is to-day often emphasized rather strongly by those engaged in it. So much so, that when we have heard them on the subject, we are sometimes left with the feeling that we ought to look on all scientific theories as mere ‘hypotheses’ in the sense of the Platonic and medieval astronomers, and that it is wrong to take any of them with the ‘liberalness’ that embroiled Galileo with the Church. They are at best, we are assured, the mathematical formulae which up to the time of writing have been found the simplest and most convenient for—well, for saving the appearances. In physics in particular there is a marked tendency to treat almost as an *enfant terrible* anyone who takes the models literally enough to refer to them in any context outside that of physical inquiry itself.¹ It would seem to follow from this that, as Plato and the astronomers believed, scientific hypotheses have no direct relation to the real nature of things.

On the other hand I find something equivocal in the public utterances of the spokesmen of science. For the same ones who have just been stressing this unpretentious view of scientific theory will frequently let drop some such phrase as ‘some day we may know’—or even ‘we now know’—when speaking, not of some particular hypothesis, but of quite general conclusions about the nature of universe, earth, or man. Moreover, if the occasion is a formal one, we often get some reference to the history of science, in terms of ‘advancing the frontiers of knowledge’, and so forth. All this indicates a very different conception of science and strongly suggests to the audience that modern science, so far from being disentitled to claim the status of knowledge, is the only reliable knowledge available to us. At the least, it suggests that the findings of any particular science are not merely tools for the application and further pursuit of that science, but have some sort of absolute validity.

Perhaps the confusion is at present unavoidable, but let us at least be clear that it *is* a confusion between two quite incompatible views. Let us see, for instance, what consequences flow from adopting the first view, namely, that scientific theories are simply hypotheses to save the appearances. This can best be done with the help of a qrotesquely over-simplified analogy. But first let me make the bearing of the analogy clear. It will contrast two different sorts of ‘knowledge’, both of which, *in the analogy*, depend on alpha-thinking; but it will *illustrate* the difference between a ‘knowledge’ which does depend on alpha-thinking and a different kind of knowledge altogether which does not. Plato and Aristotle, and others, as we have seen, taught that there was such a knowledge  and that it was accessible only to participation. But it is not necessary to believe this in order to understand the analogy.

Take a clever boy, who knows nothing about the principle of internal combustion or the inside of an engine, and leave him inside a motor-car, first telling him to move the various knobs, switches and levers about and see what happens. If no disaster supervenes, he will end by finding himself able to drive the car. It will then be true to say that he knows *how to drive* the car; but untrue to say that he knows the car. As to that, the most we could say would be that he has an ‘operative’ knowledge of it—because for operation all that is required is a good empirical acquaintance with the dashboard and the pedals. Whatever we say, it is obvious that what he has is very different from the knowledge of someone else, who has studied mechanics, internal combustion and the construction of motor-cars, though he has perhaps never driven a car in his life, and is perhaps too nervous to try. Now whether or no there is another kind of knowledge of nature, which corresponds to ‘engine-knowledge’ in the analogy, it seems that, *if the first view of the nature of scientific theory is accepted*, the kind of knowledge aimed at by science must be, in effect, what I will call ‘dashboard-knowledge’.

Francis Bacon, whose startlingly original mind was so influential in bringing about the scientific revolution, was very frank about this. Not only did he maintain that knowledge was to be valued for the *power* it gives man over nature; but he practically made success in this aim a part of his definition of knowledge. The key words he uses to distinguish the knowledge he exalts from the knowledge pursued by the Schoomen are ‘fruit’ and ‘operation’. In other words, not only ‘science’ but knowledge itself, that is, the only knowledge that is not mere trifling, is, for him—technology. Knowledge (for which Bacon, when he wrote in Latin, of course used the word *scientia*) is that which enables us to make nature do our bidding.

I think it must be acknowledged that the ‘idea’ which stands behind the particular kind of knowledge which we have come to call ‘science’ is ‘dashboard-knowledge’. I mean only that that is its *mode* of ‘knowing’. I do not of course mean that the motive by which the great scientists have been inspired has been the desire for power. The analogy is admittedly a crude one. For, while the dashboard of even the most expensive and up-to-date car is a comparatively simple affair, nature’s ‘dashboard’—that is, her exterior, accessible to the senses and the reason—is of such a marvellous and intricate complexity that many a man has counted his life well spent in mastering a tiny corner of it.

If however it *is* acknowledged, what follows? If science is merely technology, if the theories of physics in particular are mere hypotheses to save the appearances, with no necessary relation to ultimate truth, then—well, in the first place, one hopes that the car will not break down. But, in the second place, it might be argued that they should be consistently treated as such. It might be said that the theories of physics should be reserved for the purposes of physics and left out of sight altogether, when we are thinking about anything else—about the nature of perception, for instance. This would remove the foundation from under the first part of this book. But it would also have so many other, and such startling consequences, that I am not seriously alarmed.

For, in the first place, we could not limit the new and more hypothetical way of thinking to nuclear, or recent physics. The laws of gravity, for example, and of intertia, must go the same way as the electrons, as far as any ultimate validity is concerned. Secondly, you cannot really isolate one science from others in this way, nor is it the practice to do so. One has only to think of the effects of physical theory, treated as fact, on the sciences of medicine and astronomy as exemplified in radio-therapy and astrophysics. Thirdly, and most important of all for my purposes, the hypotheses do in fact, get into the collective representations; many of them are, and others soon may be, implicit in the very ‘nature’ which surrounds us, and therefore in the world in which I have to write. And lastly the withdrawal from ‘participation’, which alpha-thinking has brought about, has its advantages. The vagaries of confusion and savagery in the tribes in which anthropology finds participation most conspicuously surviving to-day, though they may well not be very reliable guides to its ancient quality among other peoples who have long since abandoned it, do nevertheless remind us of the sins of commission in thought, feeling and action of which original participation is capable. Whatever sins of omission alpha-thinking may be guilty of, we owe to it, up to now, our independence, much of our security, our psychological integrity and perhaps our very existence as individuals. When Prospero renounced his last enchantments and set sail for civilization, Ariel, it is true, remained with Caliban—but so did Setebos.

Apart from all this, there is one conclusive reason why, in spite of the technological slant of natural science, our beta-thinking is bound to *begin* with the assumption that alpha-thinking has a valid relation to truth. With collective representations like ours, what else can we do? Where else can we start from? If the physical theory of an unrepresented base *has* some such validity, so much the better. If not—even if it amounts to positive error—the way out may still lie through and not back. The best way of escape from deep-rooted error has often proved to be, to pursue it to its logical conclusion, that is, to go on taking it seriously and see what follows. Only we must be consistent. We must take it *really* seriously. We must give up double-think. For inconsistent and slovenly thought can abide indefinitely in error without any feeling of discomfort.

>¹Anyone, it has been said, may ask questions concerning wave-mechanics; but only cads talk about ‘ether’!
