# VI<br/>ORIGINAL PARTICIPATION

It is characteristic of our phenomena—indeed it is this, above all, which distinguishes them from those of the past—that our participation in them, and therefore also their representational nature, is excluded from our immediate awareness.  It is consequently always ignored by our ‘common sense’ and sometimes denied even in theory. For this reason it will be best to begin the brief series of observations which I want to make upon the history of phenomena—that is, the history of the familiar world—from the present day, and to work backwards from there to the remoter past. Our first step, then, is to trace the last stage of this development, which has led up to the collective representation with which we are familiar to-day.

Participation is the extra-sensory relation between man and the phenomena. It was shown in Chapter III that the existence of phenomena depends on it. Actual participation is therefore as much a fact in our case as in that of primitive man. But we have also seen that we are unaware, whereas the primitive mind is aware of it. This primitive awareness, however, is obviously not the theoretical kind which *we* can still arrive at by beta-thinking. For that presupposes some acquaintance with the findings of modern physics and physiology and can only be applied to the kind of collective representations that go with this. The primitive kind of participation is indeed not theoretical at all, inasmuch as it is given in immediate experience. Let us distinguish it from ours by calling it ‘original’ participation. It would however be cumbersome to add the epithet every time the word is used and I propose very often to omit it, having first made it plain here and now that by ‘participation’ I shall mean *original participation*, unless the context otherwise requires.

There is another difference between sophisticated and primitive participation. Hitherto we have spoken of *representations* and of the *unrepresented*; but we have said nothing of any ‘represented’. This raises the question whether *representation* was the proper word to use at all, or whether it is merely misleading. If an appearance can properly be called a representation, it will certainly be a representation *of* something. Just as ‘the particles’, then (the name here chosen for all that is conceived to exist *independently* of consciousness), have also been called the *unrepresented*, so, whatever is *correlative* to the appearances or representations will here be called the *represented*. This is of course a mere name, and gives as yet no clue to the nature of what is meant. I hope that further light will be thrown upon it, gradually, as we proceed. Meanwhile I must use the name, leaving the reader to make up his mind, ambulando, whether it was justified or not.

We have seen that a very large part of the collective representations is found by beta-thinking to have been contributed by the percipient’s own activity. Beta-thinking therefore inevitably assumes that a very large part of their correlative, the *represented*, is to be found ‘within’ ourselves. Consequently if *our* participation, having been first understood and accepted, by beta-thinking, as a fact, should then become a conscious experience, it would have to take the form of conscious (instead of, as now, unconscious) figuration. This is because for us, the represented is conceived as within our percipient selves; and it is only an unrepresented physical base (‘particles’) which we conceive of as without. Not so for primitives. For them the represented, too, is conceived as outside, so that there is no question of conscious figuration. It may also sometimes be detected within, but it is detected primarily without. The human soul may be one of the ‘stopping places’ for *mana*, but what differentiates the primitive mind from ours is, that it conceives itself to be only *one* of those stopping-places and not necessarily the most significant. The essence of *original* participation is that there stands behind the phenomena, *and on the other side of them from me*, a represented which is of the same nature as me. Whether it is called ‘mana’, or by the names of many gods and demons, or God the Father, or the spirit world, it is of the same nature as the perceiving self, inasmuch as it is not mechanical or accidental, but psychic and voluntary.

I have here assumed that what L&#233;vy-Bruhl and Durkheim and their followers say about contemporary primitive man is substantially correct; and it seems to me likely to be so.¹ But whether or not it is correct for contemporary primitive man, it is certainly true of historically early man. All the evidence from etymology and elsewhere goes to show that the further back we penetrate into the past of human consciousness, the more mythical in their nature do the representations become. Moreover there is no evidence to the contrary. I shall say something later on of the testimony borne by etymology. Here it must suffice to affirm categorically that, for the nineteenth-century fantasy of early man first gazing, with his mind *tabula rasa*, at natural phenomena like ours, then seeking to explain them with thoughts like ours, and then by a process of inference ‘peopling’ them with the ‘aery phantoms’ of mythology, there just is not any single shred of evidence whatever.

I do not mean, by using the word ‘fantasy’, to imply  contempt. If great scholars like Max M&#168;ller and Sir James Frazer, in seeking for the historical origins of myth, made the same mistake as the early anthropologists, it will, I hope, become apparent in the course of this and the ensuing chapters how inevitable it was that they should do so. To-day, on the other hand, partly thanks to their work, any little man, provided he is not hopelessly prejudiced, can convince himself of the contrary. The point is, not to find someone to turn up our noses at, but to grasp that fact that alpha-thinking, when men first began to exercise it, had to be directed upon *that* kind of collective representation (namely the participated kind) and not on collective representations resembling ours, which (as we shall see) are a later product of that very alpha-thinking.

For alpha-thinking, as I have defined it, is a thinking *about* collective representations. But when we think ‘about’ anything, we must necessarily be aware of ourselves (that is, of the self which is doing the thinking) as sharply and clearly detached from the thing thought about. It follows that alpha-thinking involves *pro tanto* absence of participation. It is in fact the very nature and aim of pure alpha-thinking to exclude participation. When, therefore, it is directed, as it hast to be to start with, on phenomena determined by original participation, then, at first simply by being alpha-thinking, and at a later stage deliberately, it seeks to destroy that participation. The more so because (as we shall also see), participation renders the phenomena less predictable and less calculable.

The history of alpha-thinking accordingly includes the history of science, as the term has hitherto been understood, and reaches its culmination in a system of thought which only interests itself in phenomena to the extent that they can be grasped as independent of consciousness. This culmination appears to have been reached about the close of the nineteenth century. For, along with the recent tendency of physics to implicate the observer again in the phenomena, there goes the tendency of physicists to give up alpha-thinking about phenomena and occupy themselves, as mathmeticians, only with the unrepresented.

Systematic alpha-thinking appears to have begun with astronomy. Whether this was because the movements of the heavenly bodies display a regularity which is mostly lacking in sublunary phenomena, and which would be the first therefore to attract the attention of minds beginning for the first time to interest themselves in regularity, or whether it was for some other reason, we need not consider. Astronomy is generally regarded as the *doyen* of the sciences, and a glance at its history from Greek times to the present day or thereabouts will afford some insight into the development of that exact thinking about phenomena which is called science and the effect of that development on the collective representations of Western man. I say from Greek times because, although the Egyptians and Chaldeans appear to have kept astronomical records over a very long period, we know nothing of any avowedly *speculative* thought earlier than the Greeks either on this or on any other subject.

That the collective representations to which this speculative thought was applied were of the kind already indicated, i.e., participated, is obvious enough. Apart from speculative thought, it would never have occurred to an ancient Greek to doubt that the heavenly bodies and their spheres were in one way or another representations of divine beings. Such doubt was, in fact, voiced occasionally—simply because the Greek mind was of such an incorrigibly speculative nature that there was very little that did *not* occur to it—as a purely notional possibility. But the point is that, in the early days of alpha-thinking, any such notion was a secondary speculation, and rather a wild one, about collective representations whose character made the contrary, ‘representational’, view seem the obvious one.

The systematic alpha-thinking exercised only by the thoughtful few is applied to the phenomena, that is, to collective representations which they share with the many. And we are left in no doubt by Plato’s Dialogues, and by the whole language and literature of Greece, what these, in general, were like. There it was the materialist who looked like a Berkeley and the Greek equivalent of Dr. Johnson whoud return from speculation to common sense, not by kicking a stone, but by appealing to collective representations made obvious by his upbringing, by the language he spoke and heard spoken all around him, and by the active cults which were his daily matter of fact experience. Even the atoms of Democritus were, of course, not atoms, as the word has been understood in the nineteenth and twentieth centuries. They were imagined as components of mind no less than of matter. In other words they were the only sort of atoms which alpha-thinking about participated phenomena *could* present to itself for the purpose of speculation.

It is in this light that we must approach, if we wish to understand them, not only the speculations of Plato, and Aristotle, for instance, on the nature of the stars and planets, but also the meanings of common words like *&nu;&omicron;&upsilon;&sigmaf;* (*nous*) and *&lambda;&omicron;&gamma;&omicron;&sigmaf;* (*logos*), and the whole apparatus of language by which they expressed these speculations. If we are content to translate, and to *think* ‘mind’ for *&nu;&omicron;&upsilon;&sigmaf;* and ‘reason’ or ‘word’ for *&lambda;&omicron;&gamma;&omicron;&sigmaf;*, we are in continual danger of surreptitiously substitution our own phenomena for those which they were in fact dealing with. It is not only that they speculated on whether the planets were ‘visible gods’ or only images of the gods, as statues are; on the nature of the Fifth Essence and its relation to the earthly elements; on the Anima Mundi; on whether or not the Aether, which is the substance of the spheres, has a soul, etc. The very meanings of the incidental words with the help of which they did the speculating, implied participation *of some sort*. Whereas the words into which we struggle to translate them imply the reverse. Some examples of these words will be considered in a later chapter, when it will be seen that original participation survived in an attenuated form even into the Middle Ages.

It may remove the risk of misunderstanding if I mention at this early stage that it is no part of the object of this book to advocate a return to original participation.

>¹ Compare, more recently, the last two talks in *The Institutions of Primitive Society* (A series of Broadcast Talks). Blackwell. 1954.
