# IX<br/>AN EVOLUTION OF IDOLS

It is the common opinion that, whereas we see nature pretty much as she really is, primitive man sees and archaic or early man saw her all awry through the veil of a complicated system of fancies and beliefs. If, however, the general conclusions of Chapter IV are accepted, it is clear that, whether or no archaic man saw nature awry, what he saw was not primarily determined by *beliefs*. On the other hand it was suggested in Chapter VII that what *we* see *is* so determined. If I am right therefore, there is indeed a contrast between primitive and modern consciousness and that contrast *is* connected with beliefs, but in exactly the opposite way to what is generally supposed. Precisely what beliefs about phenomena have been widely and confidently and long enough held to become actually part of a representation, is, as I have said, a matter on which opinions may well differ in any particular case. But, whether they are part of our collective representations or not, it is a fact that there are certain beliefs not only about the structure, but also about the history, of the phenomena surrounding them, which are widely, indeed almost universally, shared by civilized men in this second half of the twentieth century. There are also beliefs, only a little less confidently and a little less universally held, about the history of consciousness. As both these sets of beliefs run sharply counter to a good deal of what I have said and intend to say on the same subject, it will be well to give some indication of how and why these (in my view) mistaken beliefs arose.

But first of all, one more brief digression on the subject of science. Most of what I have said about it has connoted the experimental and practical category. Whether the theories of physics and astronomy, for instance, are truths or approximate truths, or whether they are mere hypotheses to save the appearances, the impressibe thing about them is that they work. We predict the result of an experiment, we make the experiment, with all adequate safeguards, and the prediction is verified. In the case of astronomy, although we cannot experiment, we can still predict and, in doing so, test the efficiency of our hypotheses.

>They predict many years ahead eclipses of the sun and moon; they specify the day, the hour and the extent; and their reckoning is correct—the events follow their predictions; they have discovered and recorded rules, by which it can be foretold in what year, in what month of the year, on what day of the month, at what hour of the day, in what part of their light the sun and moon are to be eclipsed; and what is foretold occurs.

These words are of course not less, but much more true of the Copernican and Newtonian hypotheses of to-day than they were of the Ptolemaic and contemporary hypotheses to which St. Augustine was referring when he wrote them in his *Confessions*¹ at about the end of the fourth century A.D. By their ‘fruits’, as Bacon would have said, we know them.

But there are to-day, alongside the practical and experimental sciences, a number of others which are, it seems to me, in a much less happy position. I suppose a large part of astrophysics, for example, to be unverifiable by any prediction or experiment; but I am concerned here more with sciences such as paleontology and a good part of geology and zoology, whose subject-matter is the past, which naturally cannot be predicted and is not either susceptible of experiment. Here we cannot say, with Bacon, ‘never mind what those tedious old fools, the Schoolmen, meant by “knowledge”; does it deliver the goods?’ For the only goods to be delivered *are*—knowledge. There is no ‘operation’, no ‘fruit’ and no emperical test of accuracy. If *their* hypotheses are not also the actual truth, they are nothing.

It seems to me that the only thing which such purely theoretical sciences really have in common with those at the technological end of the scale, is the healthy *discipline*, the open-minded attitude to fact which is, or should be, common to all whose object is knowledge, and which has itself become so much better understood and acknowledged as a result of the systematic pursuit of empirical science. But it also seems to me that they have in fact borrowed very much more than this. They have for instance accepted many of the hypotheses of sister sciences as established facts, according to them the same status in the construction of their theories as to their own first-hand observation. In this connection I have already pointed out in Chapter V that they have accepted *some* of these hypotheses, while choosing to ignore others. They have moreover borrowed half the vocabulary of hypothesis and empirical verifications and are deeply coloured by the technological mode of knowledge which that implies, though it is really quite inappropriate to them. It is almost as if they expected dashboard-knowledge to tell us how the engine was made. I believe this to be one of the reasons, though not the most important one, for the hypothetical picture of the evolution of the earth and man which began at about the end of the eighteenth century to fasten itself on men’s minds and which is to-day regarded by ordinary men (as are all but the most recent and avowedly tentative of scientific hypotheses) as palpable fact; which indeed, it may be argued, has become part of their collective representations.

At the beginning of the eighteenth century the variety of natural species was normally attributed by the botany and zoology of the day to supernatural and instantaneous creation. The eighteenth and nineteenth centuries witnessed the almost total disappearance of this tradition, reflected as it was in the elaborately classifying botany of Linnaeus, in favor of a gradual ‘evolution’. In the record of the rocks and the dovetailed panorama of organic nature, history and science together gradually divined the vestiges of a different, a ‘natural’ kind of creation, and one that was the reverse of instantaneous. Nature herself came to be seen as a process in time and the individual phenomena at any moment, instead of being fixed and parallel shapes repeated and repeated since creation’s day, were cross-sections of their own development and metamorphosis. They could be truly grasped only by looking before and after. A consideration of the incidental effecct of this on our whole conception of the significance of history, and indeed of time itself, must be deferred to a later chapter. Suffice it here to say that the upheaval was all the greater—indeed it amounted in the end to something like an explosion—because it came at a time when the mind of Europe was perhaps more disinclined to look *forward* than at any other time in its history. The backward-looking mood of the Revival of Learning had not yet died away and most men were much less concerned with the shape of things to come than with the greatness and wisdom of the ancient Greeks and Romans and the virtues of the noble savage, corrupted (it was held) by the advance of civilization.

In this chapter we are concerned with the form which the hypothesis ultimately took and its effect on the collective representations. this was naturally determined to a large extent by the existing representations to which it was applied. What were the phenomena of nature at the time when the new doctrine began to take effect, and particularly at the Darwinian moment in the middle of the nineteenth century? They were *objects*. They were unparticipated to a degree which has never been surpassed before or since. The habit, begun by the scientific revolution, of regarding the mechanical model constructed by alpha-thinking as the actual and exclusive structure of the universe, had sunk right into them. Hardy’s rustics may indeed remind us that change did not proceed everywhere at the same rate even in the English-speaking world; but for townsmen at least—in a world which was already rapidly and is now more rapidly still becoming totally urbanized—the last flicker of medieval participation had died away. Matter and force were enough. There was as yet no thought of an unrepresented base; for if the particles kept growing smaller and smaller, there would always be bigger and better glasses to see them through. The collapse of the mechanical model was not yet in sight, nor had any of those other factors which have since contributed to the passing of the dead-centre of ‘literalness’—idealist philosophies, genetic psychology, psycho-analysis—as yet begun to take effect. Consequently there was as yet no dawning apprehension that the phenomena of the familiar world may be ‘representations’ in the final sense of being the mental construct of the observer. Literalness reigned supreme.

What then had alpha-thinking achieved at precisely this point in the history of the West? It had temporarily set up the appearances of the familiar world (which the same thinking, pursued a little farther—pursued to the point which I have called ‘beta’—discovers to be so inextricably involved with man himself) as things wholly independent of man. It had clothed them with the independence and extricsicality of the unrepresented itself. But a representation, which is collectively mistaken for an ultimate—ought not to be called a representation. It is an idol. Thus the phenomena *themselves* are idols, when they are imagined as enjoying that independence of human perception which can in fact only pertain to the unrepresented. If that is, for the most part, what our collective representations are to-day, it is even more certainly what they were in the second half of the nineteenth century. And it was to *these* collective representations that the evolutionists had to apply their alpha-thinking, just as it was to the quite different representations of their own contemporaries that Plato and Aristotle had to apply theirs. Is it to be wondered at that the evolution which the former have depicted is not a real evolution of phenomena at all, but, as was pointed out in Chapter V, a factitious extrapolation—an evolution of ‘idols of the study’?

I am speaking of course of the form which the theory finally took, not of the concept of evolution itself. That is factual enough. The record of the rocks *is* a script containing stored memories of earth’s past. It is only a question of how the script is to be read. A touch of that participation which still linked the Greeks, and even the medieval observer with his phenomena, might well have led to a very different interpretation—as it did in the case of Goethe, who had that touch. But for the generality of men, participation was dead; the only link with the phenomena was through the senses; and they could no longer concieve of any manner in which either growth itself or the metamorphoses of individual and special growth, could be determined from within. The appearances were idols. They had no ‘within’. Therefore the evolution which had produced them could only be conceived mechanomorphically as a series of impacts of idols on other idols.

If the impulse to construe as process the record of the rocks and the vestiges of creation apparent in the natural order had come either a little earlier, before participation had faded, or a little later, when the iconoclasm implicit in physical analysis—and in the beta-thinking to which it can give rise—had really begun to work, man might have read there the story of the coming into being, *pari passu*, of his world and his own consciousness. As it was, all that palaeontology could take over from the experimental sciences, such as astronomy and physics, was the idols which those latter had so far succeeded in creating. Working with these, it attempted moreover to adopt the orthodox ‘geometrizing’ tradition of those sciences with a slavishness that led, in one instance at least, to results whose absurdity is only just beginning to dawn on us.

There is no more striking example than the Darwinian theory of that borrowing from the experimental by the non-experimental sciences, to which I referred at the beginning of this chapter. It was found that the appearances on earth so much lack the regularity of the appearances in the sky that no systematic hypothesis will fit them. But astronomy and physics had taught men that the business of science is to find hypotheses to save the appearances. By a hypothesis, then, these earthly appearances must be saved; and saved they were by the hypothesis of—chance variation. Now the concept of chance is precisely what a hypothesis is devised to save us from. Chance, in fact, = no hypothesis. Yet so hypnotic, at this moment in history, was the influence of the idols and the special mode of thought which had begotten them, that only a few—and their voices soon died away—were troubled by the fact that the impressive vocabulary of technological investigation was actually being used to denote its breakdown; as though, because it is something we can do with ourselves in the water, drowning should be included as one of the different ways of swimming.

>¹Bk. V, ch. iii.
