# X<br/>THE EVOLUTION OF PHENOMENA

I shall have succeeded very poorly with the opening chapters of this book, if I have not succeeded in making one thing plain. It is only necessary to take the first feeble step towards a renewal of participation—that is, the bare acknowledgement in beta-thinking that phenomena are collective representations—in order to see that the actual evolution of the earth we know must have been at the same time an evolution of consciousness. For consciousness is correlative to phenomenon. Any other picture we may form of evolution amounts to no more than a symbolical way of depicting changes in the unrepresented. Yet curiously enough, as already observed, this latter kind of evolution is just what is assumed *not* to have taken place. We look at a fossil-bearing rock and prove how things have changed by describing appearances which can never have appeared, unless there was at the same time consciousness. We fix the date of those appearances, and exclude the possibility of consciousness, by measuring the radio-active content of the rock, on the footing that the behaviour of the unrepresented has remained unchanged for millions of years.

By treating the phenomena of nature as objects wholly extrinsic to man, with an origin and evolution of their own independent of man’s evolution and origin, and then by endeavouring to deal with these objects as astronomy deals with the celestial appearances or physics with the particles, nineteenth-century science, and nineteenth-century speculation, succeeded in imprinting on the minds and imaginations of men their picture of an evolution of idols. One result of this has been to distort very violently our conception of the evolution of human consciousness. Or rather it has caused us virtually to deny such an evolution in the face of what must otherwise have been accepted as unmistakable evidence.

For the biological picture of evolution was imprinted, no less deeply than on other men’s, on the minds of those scholars—etymologists, mythologists, anthropologists—who made it their business to study the human past, and it was accepted by them, not as speculation or hypothesis, but as established fact. It was treated as part of the appearances they were setting out to save. Consequently, in their endeavours to explain the mind of early or of primative man, they set him down, in fancy, in front of phenomena identical with their own, but with his mind *tabula rasa*, and supposed the origin of human consciousness to lie in his first efforts to speculate about those phenomena. In this was was evolved the doctrine of ‘animism’, according to which the fancy of primitive man had ‘peopled’ nature with spirits. Now, in order that nature may be peopled with spirits, nature must first be devoid of spirit; but this caused the scholars no difficulty, because they never supposed the possibility of any other kind of nature. The development of human consciousness was thus presented as a history of alpha-thinking beginning from zero and applied always to the same phenomena, at first in the form of erroneous beliefs about them and, as time went on, in the form of more and more correct and scientific beliefs. In short, the evolution of human consciousness was reduced to a bare history of ideas. No doubt the history of consciousness does include the story of any number of erroneous beliefs, but the erroneous beliefs of human beings about phenomena are neither the most interesting nor the most important thing about the numan beings or about the phenomena.

It may be objected that what I have recounted in the last three chapters is itself very like a history of ideas and beliefs. This is quite true. It had to be what it was, because I wished to begin by showing how our *present* collective representations arose, and it is just a fact that these are determined by ideas and beliefs rather than—as is the case with participating consciousness—productive of them. At the same time it does raise an important question. Granted that for the past two or three thousand years the process of evolution has consisted in the gradual ousting of participation by alpha-thinking, is even the history of alpha-thinking itself just a history of thought in the ordinary sense, or can we also detect in it the subliminal working of an evolutionary process? A history of thought, as such, amounts to a dialectical or syllogistic process, the thoughts of one age arising discursively out of, challenging, and modifying the thoughts and discoveries of the previous one. Is this all we mean by the history of alpha-thinking?

The evidence points in the opposite direction. Many indications suggest that, in addition to the dialectical history of ideas, there are forces at work beneath the threshold of argument in the evolution even of modern consciousness. Go far enough back and it is obvious. The comparatively sudden appearance, after millenia of static civilizations of the oriental type, of the people or the impulse which eventually flowered in the cultures of the Aryan nations can hardly have been due to the impact of notion on notion. And the same is true of the abrupt emergence at a certain point in history of vociferously speculative thought among the Greeks. Still more remarkable is the historically unfathered impulse of the Jewish nation to set about eliminating participation by quite other methods than those of alpha-thinking. Suddenly, and as it were without warning, we are confronted by a fierce and warlike nation, for whom it is a paramount moral obligation to refrain from the participatory heathen cults by which they were surrounded on all sides; for whom moreover precisely that moral obligation is conceived as the very foundation of the race, the very marrow of its being. We owe to the Jews the pejorative significance in the word *idol*. The representative images, the totemic *eidola*, which ritually focused the participation of the surrounding Gentile nations, are either condemned by their prophets as evil, or denied as unrealities; as when the Psalmist sings:

>*Their idols are silver and gold: even the work of men’s hands.<br/>They have mouths, and speak not: eyes have they, and see not.<br/>They have ears, and hear not: noses have they, and smell not.<br/>They have hands, and handle not: feet have they, and walk not: neither speak they through their throat.*

To this I shall return later.

But even when we come to the last seven-leagued step in the development of our modern mechanomorphic consciousness, which occurred at a time when alpha-thinking was already far advanced, we are forced to the same conclusion. Why should the scientific revolution have occurred when it did, and at no other time, although men had been busy saving the appearances by abstract hypotheses for century after century? We might be tempted to answer this question by saying that it came when alpha-thinking had succeeded in developing more efficient instruments of observation, so that observation of the phenomena themselves became at last a viable and more attractive alternative to the traditional medieval practice of merely glossing Aristotle. The scientific revolution, it is often suggested, came about because men began at last to look at nature for themselves and see what happened; and we are referred to Galileo’s telescope and Jupiter’s moons. But this will hardly suffice. For although post-Copernican astronomy certainly was based on more and better first-hand observation than the old astronomy, yet in the case of physics, as Professor Butterfield has pointed out, it was the other way about. A very long step—and a very difficult one—was taken in the final ousting of participation, when the Aristotelian and medieval doctrine that all bodies come to rest, unless they are kept in motion by a ‘mover’, was at last abandoned. Yet if we base our hypotheses on the behaviour of the bodies we actually see in motion, this is the only conclusion we can possibly come to. The theory of ‘impetus’, which later developed into the concept of ‘inertia’, requires, not observation, but the abstract, geometrizing supposition, never realized in practice—at least on earth—of bodies moving through a gravity-free, frictionless vacuum. In this case therefore the change of outlook—and there could hardly be a more significant one—must have been hindered rather than helped by observation.

No. Although alpha-thinking is itself dialectical, I do not think it can be convincingly maintained that the historical development of alpha-thinking is a purely dialectical process. The evidence in such matters is naturally not of the sort that can be measured with a slide-rule or broken with a hammer, but it does not require all that fineness of perciption to discern *behind* the evolution of consciousness the operation of forces beneath its threshold. There is some internal evidence, too. Men concerned with the development of any branch of thought, if they happen also to be acutely conscious of the workings of their own minds, are sometimes surprised at the ease and the force with which ideas tending in a certain direction have come into them. They have been known to speak, not without a kind of bewilderment, of certain thoughts being ‘in the air’. The following passage from the *Autobiography* of John Stuart Mill appears to record just such an experience:

>What thus impressed me was the chapter in which Bentham passed judgment on the common modes of reasoning in morals and legislation, deduced from phrases like ‘law of nature’, ‘right reason’, ‘the moral sense’, ‘natural rectitude’, and the like and characterized them as dogmatism in disguise, imposing its sentiments upon others under cover of sounding expressions which convey no reason for the sentiment, but set up the sentiment as its own reason. . . . *The feeling rushed upon me*, that all previous moralists were superseded, and that here indeed was the commencement of a new era in thought.

The italics are mine, but the sentiments are those of that least excitable of men, John Stuart Mill. I quote them only because of the strong feeling I had, when I read them, that here, where one would most of all expect the development of thought to be simply the process of its own discourse, something else was going on underneath it. We must defer until nearer the end of any consideration of what that something may be.
