# XXII<br/>SPACE, TIME AND WISDOM

The Western type of consciousness may be said to have begun, as we saw at the end of Chapter XV, with the emergence of Greek thought from the Orient. For the Western outlook is based essentially on that turning of man’s *attention* to the phenomena, which in this book has been called alpha-thinking. This is sharply contrasted with the oriental impulse (still heard echoing in Plato) to *refrain* from the phenomena, to remain, as it were, in the bosom of the Eternal, to disregard as irrelevant to man’s true being, all *that*, in his experience, which is based on ‘the contacts of the senses’. Oriental philosophy, hardly distinguishable from oriental theology, is based, above all, on a determination to regard the sense-world as *Maya*, or illusion. It was for this reason that, on its rediscovery in the nineteenth century, it made such a strong appeal to the few who were by then becoming dimly aware that the enlightenment of the West is based on idolatry. It is clear, however, that the way of the West lies, not back but forward; not in withdrawal from the contacts of the senses, but in their transformation and redemption.

We have also seen that the rise and growth of alpha-thinking was associated with a change in man’s experience of space. It was with difficulty that *movement*, and particularly movement in a circle, was first wholly distinguished from mental activity; and this applied expecially to the celestial revolutions, which were approached in a way that suggests that what we call space was conceived rather as a kind of undifferentiated, all-enclosing continuum, or mental *mobile*, for which perhaps *wisdom* is the best modern word we can find. Space, as a mindless, wisdomless, lifeless void, was not a common notion at any time before the scientific revolution; thus at the close of Chapter XI we saw how the experience of space differed from our own, even as recently as medieval times. To the remnant of participation which then still survived, man, as microcosm, was placed at the centre of the macrocosm; but the point was, that he was an *organic* centre. The spatial aspect of the relation was incidental. It is only when space itself has become an idol—when it has become simply the *absence of phenomena, conceived in the phenomenal mode*—that perspective takes the place of participation. For the mode of vision which perspective reproduces, each pair of eyes is placed at the centre of a purely spatial sphere, and any organic relation there may be is incidental.

If therefore we should wish to revive in ourselves the faculty of experiencing spatial form as representation, and if we should wish to seek assistance in doing so, from the past history of man, we shall do well to look backwards to the East, along the path that led through the Greeks to the scientific revolution.

We have seen however that there is another line along which we can also look back to the same source. In Chapter XVI we saw that, long before the alpha-thinking of the Greeks had begun its long task of eliminating participation from human consciousness, the Jewish nation, with a different impulse and a more considered purpose, had initiated the like process. In their case there was no question of turning their attention to the phenomenon for its own sake, or at all. The killing out of participation was the end, in itself, and imagery of all kinds was the quarry marked out for destruction.

It has often been pointed out that we find reflected in the early literature of the Jews and entirely new feeling for the significance of history, and perhaps of time itself. It is in their apocalypses that we first detect a conception of history as something which had a beginning and is moving towards an end. The apocalypses have even been pointed to as the earliest example of something that could be called a doctrine of evolution. It has perhaps not been so often remarked that a peculiar sense of the significance and shape of time is also reflected in the Hebrew language. Not only, for example, does the Hebrew verb possess no present tense, as we understand it in the Aryan languages; the past being used for every moment up to the present, and the future for every moment from the present on. Not only is this the case, but the past and future are interchangeable in ways which it is difficult for us to understand. More than one Hebrew grammarian, for instance, has declared that the past tense was used for prophecy and the future for history.

Once again we notice a sharp contrast with what had gone before. The oriental conception of time was essentially cyclic. The picture was one of eternal repetition rather than of beginning, progress and end, and the path of the individual soul to the bosom of eternity was a backward path of extracation from the wheels of desire in which it had allowed itself to become involved. To reach, or to resume, the Supreme Identity with Brama, with the Eternal, was the object and its achievement was a matter which lay directly between the individual and the Eternal. The Semitic way, on the other hand, was a way forward through history and it was a way, shared indeed by the individual, but trodden by the nation as a whole.

In a study such as this, which necessarily attempts to cover a great deal of ground in a very short space, one should beware of overstressing a resemblance to make a neat parallel. But I think it is true to say that, just as by looking back through the Greek mind, we bring to life the apprehension of form in space as an image or representation, so, by looking back through the Jewish mind, we bring to life the apprehension of form in time—that is, of events themselves, as images, whether of the past or future, or of a state of mind.

The second is a far more difficult achievement for us than the first. But I believe that anyone who would well consider the way of experiencing Old Testament history, which is implied in the Psalms and in the Jewish liturgy, and then again in Christian are before the Reformation, would understand what I mean. To immerse oneself in the medieval Mystery plays and in those sequences and parallels between Old and New Testament, which are the very backbone, the essential formal principle of the Cathedral sculptures, is to feel that, in one most real sense, the Old Testament was lost with the Reformation.

For non-participating consciousness it is either, or. A narrative is *either* a historical record, *or* a symbolical representation. It cannot be both; and the pre-figurings of the New Testament in the Old, and the whole prophetic element in the Old Testament is now apt to be regarded as moonshine. In a parallel sphere, however—the life-history of the individual man—it is already no longer taken quite so confidently for granted that the historical and the symbolical are contradictories. In the nineteenth century it required the powerful imagination of a John Keats to perceive that ‘every man’s life is a perpetual allegory’. In our own day the development of psychology alone has made this possible for much more ordinary men. Though not many may agree with him, a man is no longer regarded as a lunatic, who divines that the the things which happen to a person, and the order in which they happen, may be as much a part of him as his physical organism. And it seems to lie in the natural order of things that, with the further increase of final participation, this perception should be extended to the biographies of nations and races, and of humanity as a whole.

All things considered, before we reject out of hand the possibility of any imaginal principle in time and the events of history, we should do well to consider how we are getting on with our own conception both of time and of space.

The conception of space as an unlimited or three-dimensional void—a kind of extrapolated ‘perspective’—which came in with the disappearance of participation, is still of course the ordinary man’s concept. It held good for science, too, until the end of the nineteenth century. The indications that it is now proving inadequate are so numerous that I do not need to stress them. When, for instance, we are told that space must be conceived as spherical, or asked to think in terms of a ‘space-time continuum’, we can hardly avoid the conclusion that the old, or rather the still young, ‘idol’ of infinity as a ‘going on for ever’, whether in space or time, is showing unmistakable signs of strain. There seems to be a strong tendency, both in dealing with the periphery and in dealing with the centre of the physical universe, to substitute what are in effect thought-patterns for plausible and seriously supposed spatial apparatus. Is not the rather hectic picture of a universe expending in all directions with almost infinite rapidity, in essence a geometrical rather than a physical notion? I am told at all eventts that it bears a marked resemblance to projective geometry. ‘It appears,’ said Lord Russell, broadcasting in April 1955 on the death of Einstein,

>that the universe is of finite size, although unbounded. (Do not attempt to understand this unless you have studied non-Euclidean geometry.) It appears also that the universe is continually getting bigger.

We turn from the periphery to the infinitesimal centre of our ‘perspectivized’ space, and we hear the same voice in the same broadcast assuring us that:

>Nobody before quantum theory doubted that at any given moment a particle is at some definite place and moving with some definite velocity. This is no longer the case. The more accurately you determine the place of a particle, the less accurate will be its velocity; and the more accurately you determine the velocity, the less accurate will be its position. And the particle itself has become something quite vague, not a nice little billiard ball as it used to be. When you think you have caught it, it produces a convincing alibi as a wave and not a particle. In face, you know only certain equations of which the interpretation is obscure.

The reader will be aware that in this book I have called that ‘something quite vague’ by the name either of ‘the particles’ or of ‘the unrepresented’ and have then, for reasons given, largely dismissed it from consideration. This is perhaps the place to say a final word about it. Physical science postulates an unrepresented, as a something which is independent of our consciousness in a way, or to an extent to which the phenomena are not. Our consciousness is, however, not independent of *it*; for it is in response to its stimulus that our senses and our figuration and thinking together construct the phenomenal world. It has however lately been growing apparent that all attempts to conceive the unrepresented in terms of idol-matter in idol-space and idol-time break down. Approaching it this way, we learn only that by taking it up into mathematical equations we can produce startling technological results.

Two consequences seem to follow. Firstly, it would be rash to assume that there is no other approach than the mathematical one. Who can affirm, and on what evidence, that we may not also learn to approach the unrepresented by way of enhancine our figuration,¹ so as to make it a conscious process, as well as by the path of mathematical hypothesis? For sensation and figuration are the—at present unconscious—moment in which we actually meet the unrepresented (or, at least, encounter its resistance) in experience, as distinct from applying alpha-thinking to it afterwards. In this way we should gradually eliminate the unrepresented by rendering it phenomenal. It, too, would take its place among the collective representations. We should then at least find out whether what I have said about the phenomena can, or cannot, in the last resort be applied to the (as yet) unrepresented also; that is to say, whether or no they are representations of the collective unconscious. Certainly, the ‘something quite vague’ which can be coaxed into producing an atomic explosion does not look much like a collective unconscious—but then neither did the *represented*, which underlies the ordinary appearances, look like one—until we started thinking seriously about them.

Secondly, it would be rash to dismiss out of hand that different, and essentially representational, conception of time and space, which I mentioned at the beginning of this chapter. Which of the two is the *cul de sac* and which is the highway; whether the human mind is likelier to get somewhere by thinking of man as surrounded by a cosmos or sphere of wisdom; or by trying to think that emptiness is sphericalk and of finite size, although unbounded and getting bigger, are questions which everyone will decide for himself. It is, at all events, the former conception (as the reader will by now be aware) upon which the whole argument of this book converges; and from now on I shall assume its validity.

We may think of the cosmic wisdom as related to the appearances rather as, in men, the inner, unspoken word (the *verbum cordis, verbum intellectus*, of which Aquinas wrote) is related to the word (*vox*) that is actually vocalized. At least it is only on some such basis that we can ever hope to understand such a phenomenon as the history and literature of the Jews, or its culmination in Christianity, in a way which does not simply cut us off from the accumulated wisdom and insight of the past.

In Chapter XVI somthing was said of the part played by the Jewish impulse in the development of the Western world. If we would go farther and consider its place in the whole history of man, we can, I believe, best do so by reflecting on the nature of *memory*. Just as, when a word is formed or spoken, the original unity of the ‘inner’ word is polarized into a duality of outer and inner, that is, of sound and meaning; so, when man himself was ‘uttered’, that is, created, the cosmic wisdom became polarized, in and through him, into the duality of appearance and intelligence, representation and consciousness. But when creation has become polarized into consciousness on the one side and phenomena, or appearances, on the other, memory is made possible, and begins to play an all-important part in the process of evolution. For by means of his memory man makes the outward appearances an inward experience. He acquires his self-consciousness from them. Whe I experience the phenomena in memory, I make them ‘mine’, not now by virtue of any original participation, but by my own inner activity. It is from this activity in memory, it will be recalled, that the human word, according to Aquinas, ‘proceeds’. For, once the phenomena are ‘mine’, I can reproduce them in the form of words.

This, the human word, for Aquinas (as we saw in Chapter XIII), proceeds from the memory, as the Divine Word proceeds from God the Father. We shall understand the place of the Jews in the history of the earth, that is, of man as a whole, when we see the Children of Israel occupying the position in that history which memory occupies in the composition of an individual man. The Jews, with their language trailing vestiges of the world’s Creator and their special awareness of history, were the dawning memory in the human race. They too tore the phenomena from their setting of original participation and made them inward, with intent to reutter them from within as word. They cultivated the *inwardness* of the represented. They pin-pointed participation to the Divine Name, the I AM spoken only from within, and it was the logic of their whole development that the cosmos of wisdom should henceforth have its perennial source, not without, and behind the appearances, but within the consciousness of man; not in front of his senses and his figuration, but behind them.

>¹ As Goethe did (cf. p. 138)
