# XVII<br/>THE DEVELOPMENT OF MEANING

In the course of this book many scattered references have been made to words and language. It is desirable that some attempt should now be made to draw the threads together.

When we are disputing about the proper meaning to be attached to a particular word in a sentence, etymology is of little use. Only children run to the dictionary to settle an argument. But if we would consider the *nature* of meaning, and the relation between thought and things, we cannot profitably dispense with etymology. It is long since men gave up the notion that the variety of natural species and the secrets of their relation to each other can be understood apart from their history; but many thinkers still seek to confine the science of language, as the Linnaeans once confined botany, within a sort of network of timeless abstractions. Method, for them, is another name for classification; but that is a blind alley.

Now etymology depicts the process of language in time. And it is a commonplace of the subject that, whatever word we hit on, if we trace its meaning far enough back, we find it apparently expressive of some tangible, or at all events, perceptible object or some physical activity. *Understanding* once meant ‘standing under’, and abstractions like *concept* and *hypothesis* merely disguise, in the garb of a dead language, a similarly humble origin. Even *right* and *wrong* are said to have once meant ‘straight’ and ‘sour’.

In much more recent times we can observe the evolution of a great deal of the emotional and psychological meaning in contemporary words out of an astrological, chemical, or physiological past. Many people are aware, without turning to a dictionary, of what *disposition, influence, melancholy*, etc. used to mean, and I have already referred in Chapter XII to the fact that similar changes are *still going on* in the case of such words as *heart* and *blood*. It would be in line with the general process of etymological change if, in future, the meaning of *heart* should become purely emotional, some other word such as *cardium* being appropriated to the physical organ.

Here and there, it is true, we may observe a change in the opposite direction; and it is certainly striking that the most abstract of all abstract terms—*relation*—should have become capable of signifying a solid, three-dimensional aunt or cousin. But these are the rare exceptions. Throughout the recorded history of language the movement of meaning has been from concrete to abstract.

I am here using the word ‘abstract; in its broadest, and admittedly vague, sense, to cover everything in the familiar world we talk about, which is not, actually or theoretically, accessible to the senses; everything which a nineteenth-century logician would have termed an ‘attribute’; and which some twentieth-century philosophers classify as a mere part of speech. In this sense *melancholy* and *a kind heart* may be as much abstractions as *concept* and *hypothesis*—it depends how we think of them. How we ought to think of them may be disputed, and indeed I am engaged in disputing it. But it is enough for my present purpose that nearly everybody today thinks of them as divorced from the ‘appearances’ of nature which are accessible to the senses—in a way which nearly everybody before the scientific revolution did not.

Systematic reflection on the *history* of language hardly began before the second half of the nineteenth century, when idolatry, as we have seen, was already near its culminating point; and when it had already, as described in Chapter IX, distorted the picture which men formed of the remote past. It was against this background, therefore, that the philologists of the nineteenth century sought to account for that unmistakable, semantic progress from concrete to abstract—or from ‘outer’ to ‘inner’—to which I have just referred. In those circumstances, their answer to the problem was—metaphor. Before speech was invented, they said, primitive man lived in a world, except for details, very much like ours. His next step was to invent simple words for the simple things he saw about him—trees and animals, the sun and the moon, and so forth. And then, when his reason had evolved, and he found he needed words in which to express his inner life, he used these simple words again, but this time as metaphors. Herbert Spencer and Max Müller went further than this and added that. later on, men made the mistake of taking their own metaphors literally; and that this was the origin of mythology. Mythology, said Müller, is ‘a disease of language’.

Of course, as time went on (they said), the metaphors ‘faded’. We no longer call up any mental image of ‘standing beneath’, when we use the word *understand*, or of a physical ‘pressing out’, when we speak of *expressing* a sentiment or an idea. The progress was assumed to be from the metaphor, through the trope (which is a kind of moribund metaphor—as when we speak of following the *thresd* of an argument), to the ordinary straightforward ‘meaning’. But, whatever meanings its words might bear to-day, language was considered historically as a tissue of faded or dead metaphors.

Now there is no doubt that in the last few centuries the meanings of quite a number of the words with which we endeavour to express psychological facts or opinions have come into being in just this way—by deliberate transference from the outer world to the inner. *Emotion* is probably an example. But it is equally certain that the great majority have not. If we look into them, we find that they point us back, not to metaphor, but to participation; whether, like *disposition, influence*, and many others, through astrology, or whether, like *temper* and *humour*, through the old physiology, or whether, without being traceably connected with any particular system of thought, in one way or another they stem from a time before that exclusive disjunction between outer and inner, which the term ‘metaphor’ presupposes. Such is the case with many of the oldest words in the language—like *heart* and *blood*, to which I have already referred. Moreover, many much more recent words, to which a simple metaphorical origin may be hastily attributed, will be found on closer examination to betray similar birth-marks. *Depression*, for instance, would seem at first sight to be in the same class as *emotion*. But the evidence collected by the Oxford Dictionary suggests that its psychological significance did not, in fact, originate in a spatial metaphor (such as we use, when we speak of being ‘on top of the world’), but as a literal discription of the state of the ‘vital spirits’.

Many years ago, in a book called *Poetic Diction*, I drew attention to another fatal objection to this theory that words which to-day have a mental or emotional content acquired that content originally as a metaphorical extension of their meaning. It is this. If we find language growing more and more metaphorical, the further back we go into the past, what possible justification can there be for assuming a still earlier time when it was not metaphorical at all? Thus, Max Müller postulated a ‘metaphorical period’, during which the progress from literal to metaphorical meanings must have taken place. But, what is this but a purely arbitrary surmise? And it is not highly improbable? Why was such an assumption found necessary? Simply in order to make the evidence presented by the history of language fit in somehow or other with that ‘evolution of idols’, to which I have referred in Chapters V and IX.

It would take a very long time to trace all the influences exerted by preconceptions of this nature on the theories which men have formed about the origin and development of language, and even on lexicography itself. They are most easily detected by the train of inconsistencies they have left in their wake. Take, for instance, the old philological teaching of the building up of inflected and complex words from simple ‘roots’ of speech. Some languages, among which Hebrew is probably an outstanding example, are clearly formed about a relatively small number of consonant-groups consisting of three or even two letters each. Here is the bare fact. But what we make of it is all too likely to depend on the preconceptions with which we approach it. If we have preconceived a world in which the earliest speakers were surrounded by idols in all respects like our own, we shall treat these consonant-groups practically as ‘words’, and shall attribute to them meanings which were wide because they were generalized from particulars. This is what the philologists did; and it is particularly interesting to watch Max Müller relating this ‘root’ concept, as it was presented in his time, to his theory of a ‘metaphorical period’, to which I have already referred.

He invented a distinction between *radical* metaphor and *poetical* metaphor.

>I call it a radical metaphor when a root which means to shine is applied to form the names, not only of the fire or the sun, but of the spring of the year, the morning light, the brightness of thought, or the joyous outburst of hymns of praise. Ancient languages are brimful of such metaphors, and under the microscope of the etymologist almost every word discloses traces of its first metaphorical conception.

>From this we must distinguish *poetical* metaphor, namely, when a noun or verb, ready made and assigned to one definite object or action, is transferred poetically to another object or action. For instance, when the rays of the sun are called the hands or fingers of the sun.¹

The assumption is, that men had on their lips the roots and in their minds the meanings, very much as we have words and their meanings to-day, and then proceeded to ‘apply’ them to a varied selection of phenomena. But, as was pointed out in the book already referred to,² this assumption is inconsistent in two respects with all that we know of primative languages. Among very primitive and otherwise almost wordless peoples very short words are exactly what we do *not* find. Anthropologists tell us, instead, of the ‘holophrase’ or long, rambling conglomeration of sound and meaning. Words grow longer, not shorter, the nearer we get to the end of our backward journey towards the origin of speech. Secondly, a word meaning ‘to shine’ in general, as distinct from any particular kind of shining, is the very thing which a primitive mind is incapable of grasping. Indeed, much simpler generalizations, such as ‘tree’—as distinct from a coconut-tree or a gum-tree—are equally beyond it. If, therefore, in any language the roots were there from the beginning, then, whatever else they were, they cannot have been words devised by men for the purpose of expressing general ideas.

I do not believe, then, that there is any such thing as a ‘radical metaphor’. But I believe that reflection on the working of metaphor may nevertheless be a good approach to reflection on the nature of roots. For it is the peculiarity of metaphorical language that, at first sight, it does often resemble very closely the language of participation; though upon closer examination its existence is seen to depend precisely on the *absence* of participation.³ It is at all events important to have made some such examination before we approach the wider question of the nature and origin of language.

>¹ *Science of Language*, p. 451.

>² *Poetic Diction*, 2nd Edition, Faber 1952.

>³ Cf. p. 127.
