## XIII<br/>THE TEXTURE OF MEDIEVAL THOUGHT

Once the fact of participation is granted, the connection between words and things must, we have seen, be admitted to be at any time a very much closer one than the last two or three centuries have assumed. Conscious participation, moreover, will be aware of that connection; and original participation was conscious. It is only if we approach it in this light that we can hope to understand the extreme preoccupation of medieval learning with words—and with grammar, dialectic, rhetoric, logic and all that has to do with words. For words—and particularly nouns—were not then, and could not then be regarded as *mere* words. I ws taught in my first class at school to recite aloud with the rest of the class: ‘A noun is the name of anything,’ and the philosophers, from Plotinus to Aquinas, were wont to treat at the same time of the words and the things under the inclusive topic of ‘names’. Thus, Dionysius in his *De Divinis Nominibus*, and Aquinas in the 13th Quaestio of Part I of the *Summa* (‘concerning the names of God’) and in the little treatise *De Natura Verbi Intellectus* and elsewhere, are both concerned, not with philology but with epistemology and metaphysics.

In the last two chapters I have said a little of the world as it was for the common man and a little of the world as it was for science immediately before the scientific revolution. Now I am to say a little of the world as it was shown forth in philosophy. In all cases the plan of this book as well as the time at my disposal both for study and for writing, have determined that that little must be a very little indeed. I am only too well aware that a whole book, instead of a chapter, would not be too much to give to the philosophy alone of that lost world. Once again, it *is* a lost world—although the whole purpose of this book is to show that its spiritual wealth can be, and indeed, if incalculable disaster is to be avoided, *must* be regained. No good can come of any attempt to hark back to the original participation from which it sprang.

That lost world, then, was a world in which both phenomenon and name were felt as representations. On the one hand ‘the world conceived in the mind is representative of the whole of that which is realized in thought’ (*Verbum igitur in mente conceptum est repraesentativum omnis ejus quod acta intelligitur*).¹ But on the other hand the phenomenon itself only achieves full reality (*actus*) in the moment of being ‘named’ by man; that is, when that that in nature which it represents is united with that that in man which the name represents. Such naming, however, need not involve vocal utterance. For the nature or word is not mere sound, or mere ink. For Aquinas, as for Augustine, there are, anterior to the uttered word, the intellect-word, the heart-word and the memory-word (*verbum intellectus, verbum cordis, verbum memoriae*). The human word proceeds from the memory, as the Divine Word proceeds from the Father.² Proceeds from it, yet remains one with it. For the world is the thought of God realized through His Word. Thus, the Divine Word is also *forma exemplaris*;³ the phenomena are its representations;  as the human word is the representation of *intellectus in actu*. But, once again, the phenomenon itself only achieves its full reality (*actus*) in being named or thought by man; for thinking in act *is* the thing thought, in act; just as the senses in act, are the things sensed, in act. (*Intellectus in actu est intelligible in actu; sicut sensus in actu est sensible in actu*).⁴ And elsewhere St. Thomas expressly ratifies the dictum of Aristotle in his *De Anima*, that ‘the soul is in a manner all things’: (*Anima est quodammodo omnia*).⁵

It is against a background of thoughts like these, and of the collective representations on which they were based, that we must see the medieval conception of the Seven Liberal Arts, with Grammar at their head, followed immediately by Rhetoric and Dialectic. To learn about the true nature of words was at the same time to learn about the true nature of things. And it was the only way. We may reflect how the meaning of the word *grammar* itself has been polarized, since the scientific revolution, into the study of ‘mere’ words, on the one hand, and., on the other, into the half-magical *gramarye*, which altered its form to *glamour* and was useful for a season to the poets, before it was debased. One may reflect also on the frequent appearances made by Grammar and the other liberal arts, as persons, in medieval allegory, and how easily and naturally they mingle there with the strange figure of the Goddess Natura—at once so like and so unlike the Persephone of Greek mythology. This might easily lead us into a consideration of allegory itself—a literary form which is so little to our taste, and yet was so popular and all-pervasive in the Middle Ages. Is it not clear that *we* find allegory desiccated precisely because, for us, mere words are themselves desiccated—or rather because, for us, words are ‘mere’? For us, the characters in an allegory are ‘personified abstractions’. but for a man of the Middle Ages Grammar or Rhetoric, Mercy or ‘Daunger’, were real to begin with, simply *because* they were ‘names’. And names could be representations, in much the same solid-feeling way as things were.

For this very reason we are in some danger of confusing their allegory with the ‘symbolism’ in which we ourselves are again beginning to be interested, or at least judging them by the same standards. This is an error. Symbolism often expresses itself in language, as so much else does, though it can also express itself through other media. Yet the essence of symbolism is, not that words or names, as such, but that things or events themselves, are apprehended as representations. But this, as we have seen, is the normal way of apprehension for a participating consciousness. *Our* ‘symbolical’ therefore is an approximation to, or a variant of, *their* ‘literal’. Even when they got down to the bedrock of literal, they still experienced that rock as a representation. And so Aquinas, in dealing with the use of language in Holy Scripture, first divides its meaning into *literal* and *spiritual* and then subsumes the *allegorical* (and certain other) interpretations under the heading of *spiritual*. But when he comes to the *sensus parabolicus* (which is our ‘symbolical’) he includes it in the literal (*sub literali continetur*). When, for example, in the Bible, ‘the right arm of God’ is spoken of, ‘It is not the figure, but the figured which is the literal meaning’.⁶ All this will bear some meditation.

Indeed, to understand how the word ‘literal’ has changed its meaning is to understand the heart of the matter. For our problem is, precisely, to transport ourselves into the interior of minds, for which the *ordinary* way of looking at, and of thinking about, phenomena, was to look at and to think about them as appearances—representations. For which, therefore, knowledge was defined, not as the devising of hypotheses, but as an act of union with the represented behind the representation. And it is only by reconstructing in imagination, and not just in theory, the nature of the representations they confronted that we can hope really to understand the mode of their thinking. If we approach it from this end, instead of, as is usual, by way of our own representations and our own consequent distortions of the then meanings of their terms, then the Scholastic terminology does indeed spring into life for us—form and matter, *actus* and *potentia*, species, essence, existence, the active and the passive intelligence, and the rest. We must forget all about our ‘laws of nature’, those interposed, spectral hypotheses, before we can understand the ‘forms’ of medieval scholasticism. For the forms determined the appearances, not as laws do, but rather as a soul determines a body; and indeed the animal and human soul was defined as the ‘form’ of the body. We must forget all about causality, as we understand it, if we want to understand how the form was also *causa exemplaris*. But there is not anything to forget, for we have not even a transmuted survival, of that *actus:potentia* polarity, which was the very life-blood of Scholastic thought, central in its heart and manifest, through its capillaries, at all points of its surface organism. Being is potential existence; existence actualizes being. Yet, in the universe, *actus* preceded *potentia*; for out of potentiality a subject cannot be brought except by a being that is actual. The being of God is wholly actual, and is at the same time His existence; but, for creatures, it is only their *existence* which actualizes—actualizes not their own being, but the being of God, which they participate. Everywhere around us we must see creatures in a state of *potentia* being raised to *actus*: and yet, behind the appearances, the *actus* is already there.  What is the intellectual soul but the potentiality of determining the species of things? And what are the phenomena themselves? *Actually* the likenesses or representations of all sorts of ‘species’—bit *potentially* (that is, in the condition described as *in potentia*) immaterial in the soul itself.⁷ Phenomena and mind in perpetual interplay, with ‘species’ hovering somewhere between them as the moment in which the one becomes the other—*Anima enim quasi transformata est in rem per speciem*.⁸

‘Knowledge’, for such a consciousness, was conceived of as the perfection or completion of the ‘naming’ process of thought. In ordinary thinking or speaking, as in perception, the participation was a half-conscious process. But knowledge was an actual union with the represented behind the representation. ‘The knowledge of things that are, *is* the things;. (*Cognito eorum, quae sunt, ea, quae sunt, est*) wrote John Scotus Erigena in the ninth century, quoting Dionysius. ‘Nothing’, wrote Aquinas, ‘is known except truth—which is the same as being.’ (*nihil enim scitur nisi verum, quod cum ente convertitur*)⁹ Or, as a mean between *potentia* and *actus*, it was the process of actualization of the soul’s potentiality to become what it contemplated, and thus, a stage on its journey back to God. God’s own knowledge was alike the cause of all things and identical with His substance, and man participated in the being of God. Indeed, it was only by virtue of that participation that he could claim to *have* any being.

Now, participation as an actual *experience*, is only to be won for our islanded consciousness of to-day by special exertion. It is a matter, not of theorizing, but of ‘imagination’ in the genial or creative sense of the word, and therefore our first glimpse of it is commonly an aesthetic experience of some sort, derived from poetry or painting. And yet this experience, so foreign to our habit, is one which we positively must acquire and apply before we can hope to understand the thought of any philosopher earlier than the scientific revolution. Without it we shall not really understand what they mean when they use the commonest terms—species and genus, form and matter, subject and accident, cause and effect. Instead, we shall clumsily substitute a meaning of our own. In the work of Thomas Aquinas, in particular, the word *participate* or *participation* occurs almost on every page, and a whole book could be written—indeed one has been written¹⁰—on the uses he makes of it. It is not a technical term of philosophy and he is no more concerned to define it than a modern philosopher would be, to define some such common tool of his thought as, say, the word *compare*. Only in one passage, from the whole of his voluminous works, according to M. Geiger, did he feel it necessary to indicate its meaning, and this he did principally by illustrating it. Thus, after telling us that the species participates the genus, and the accident the subject, that matter participates form and effect participates cause, he gives us a glimpse of what all these participations signify to him, by adding: “Suppose we say that air participates the light of the sun, because it does not receive it in that clarity in which it is in the sun.”¹¹

At one end of the scale the subject participates its predicate¹²; at the other end, a formal or hierarchical participation *per similitudinem* was the foundation of the whole structure of the universe; for all creatures were in a greater or lesser degree images or represeentations, or ‘names’ of God, and their likeness or unlikeness did not merely measure, but *was* the nearer or more distant emanation of His Being and Goodness in them. It was a spiritual structure, and much of it lay beyond the world of appearance altogether. Angels, for example, are not simply the subject of a separate work, or a separate chapter of the *Summa*, but occur everywhere in it and are as likely to be referred to in a purely epistemological, as in a cosmological, context.

It will be well to point out here that, if I have concentrated on one particular medieval philosopher, rather than attempted a conspectus of the whole field of medieval philosophy or theories of knowledge, it is because that is the method which a history of consciousness, as distinct from a history of ideas, must adopt. It must attempt to penetrate into the very texture and activity of thought, rather than to collate conclusions. It is concerned, semantically, with the way in which words are used rather than with the product of discourse. Expressed in terms of logic, its business is more with the proposition than with the syllogism and more with the term than with the proposition. Therefore it must particularize. It must choose some one, or at best a few points, for its penetration. It is a question of making the best choice, and to me the best choice seemed to be the language and thought of Thomas Aquinas. I could probably have found more sensational illustrations of participation in, for example, Erigena or Albertus. For the Arabians, participation—with a particular intellectual emphasis—was so complete as practically to excluse individual human identity. I should, I think, have found fewer illustrations among the Nominalists, but they can fairly be regarded as forerunners of the scientific revolution, in whom the decline of participation cast its shadow before. Moreover, in the mind of Aquinas, with his enormous erudition, the whole corpus of medieval thought is in a manner recapitulated; and he is as sober as he is profound.

>¹ *Summa Theologica*, 12, Qu. 34. a. 3.

>² *De Differentia Divini Verbi et Humani; De Natura Verbi Intellectus*, etc.

>³ *Summa*, 12, Qu. 3, a. 8, ad 2.

>⁴ Ibid., 12, Qu. 12, a. 2. 3.

>⁵ Ibid., 12. Qu. 14. 2. I.

>⁶ *Summa*, 1a, Qu. 1, a. 10, ad 3. And cf. “p.75 above”

>⁷ Ibid., 1a, Qu. 79, a 4, ad 4.

>⁸ Aquinas, *De Natura Verbi Intellectus*.

>⁹ *Summa*, 1a, Qu. 1, a 1, 2.

>¹⁰ L.-B. Geiger, *La Participation dans la Philosophie de S. Thomas d’ Aquin.* Paris, 1942.

>¹¹ *De Hebdomadibus*, cap. 2.

>¹² Cf. p.31
