# XIX<br/>SYMPTOMS OF ICONOCLASM

We have seen that the theory of metaphor, as the means by which language originally acquired its ‘inner’meanings, is incorrect. But it is important to remember how it arose. It arose because there *is* a close relation between language as it is used by a participating consciousness and language as it is used, at a later stage, metaphorically or symbolically. When we use language metaphorically, we bring it about of our own free will that an appearance means something other than itself, and, usually, that a manifest ‘means’ an unmanifest. We start with an idol, and we ourselves turn the idol into a representation. We use the phenomenon as a ‘name’ for what is not phenomenal. And this, it will be remembered, is just what is characteristic of participation. Symbolism, as we saw in Chapter XI, is made possible by the elimination of participation. But at the end of Chapter XVI it was observed that in certain circumstances this may give rise to a new kind of participation—one which could no longer be described as ‘original’.

What then has occurred? If we rapidly review the whole historical development of ‘the word’, we must say that, as soon as unconscious or subconscious organic processes have been sufficiently polarized to give rise to phenomena on the one side and consciousness on the other, *memory* is made possible As consciousness develops into self-consciousness, the remembered phenomena become detached or liberated from their originals and so, as images, are in some measure at man’s disposal. The more thoroughly participation has been eliminated, the more they are at the disposal of his imagination to employ as it chooses. If it chooses to impart its own meaning, it is doing, *pro tanto*, with the remembered phenomena what their Creator once did with the phenomena themselves. Thus there *is* a real analogy between metaphorical usage and original participation; but it is one which can only be acknowledged at this high, or even prophetic, level. It can only be acknowledged if the crude conception of an evolution of idols, which has dominated the last two centuries, is finally abandoned, or at all events is enlightened by one more in line with the old teaching of the Logos. There is a valid analogy *if*, but only if, we admit that, in the course of the earth’s history, something like a Divine Word has been gradually clothing itself with the humanity it first gradually created—so that what was first spoken by God may eventually be respoken by man.

This granted, we can see how language, in the course of its history, has indeed mediated the transformation of phenomena into idols. But we can also see how, by reason of this very fact, *within* man the phenomena have gradually ceased to operate as compulsive natural processes and have become, instead, mere memory-images available for his own creative ‘speech’—using ‘speech’ now in the wide sense of Aquinas’s ‘word’.

We should expect, accordingly, that, with the progressive decrease of participation throughout the Graeco-Roman, or Aristotelian age, we should find a growing awareness—however faint—of this capacity of man for creative speech. And we should expect to find a marked increase in that awareness after the scientific revolution. It is what we do find. Let us take, for example, the Romantic theory of the ‘creative imagination’ and glance briefly at its previous history. Premonitory hints of an attribution of ‘creative’ power to man as artist or poet, appear as early as the first Christian century, with Dio Chrysostom. A century later Philostratus maintained of the works of Pheidias and Praxiteles, that:

>Imagination made them, and she is a better artist than imitation; for where the one carves only what she has seen, the other carves what she has not seen.

By the third century Plotinus is maintaining that:

>If anyone disparages the arts on the ground that they imitate nature, we must remind him that natural objects are themselves only imitations, and that the arts do not simply imitate what they see but reascend to those principles (λογοι) from which Nature herself is derived.

For Scaliger in the sixteenth century (who was closely followed by Sidney in his *Apologie for Poesie*) the poet is one who ‘maketh a new Nature and so maketh himself as it were a new God’.¹

Choleridge’s doctrine of the primary and secondary imagination, when it came, and the whole Romantic stress in England and Germany on the ‘creative’ function of art and poetry was, then, by no means a wholly new adventure in thought. It was rather that the whole attitude to nature, which it implied, had been rendered acceptable to a much wider circle by the rapidly increasing idolatry of the seventeenth and eighteenth centuries. Something very much like it had already been thought by a few. It became almost a popular movement in a world beginning at last to hunger for iconoclasm.

We have already had occasion to note the close relation between the apprehension of images and the making of them. As long as nature herself continued to be apprehended as image, it sufficed for the artist to imitate Nature. Inevitably, the life or spirit in the object lived on in his imitation, if it was a faithful one. For at the same time it could not help being more than an imitation, inasmuch as the artist himself participated the being of the object. But the imitation of an *idol* is a purely technical process; which (as was quickly discovered) is better done by photography. To-day an artist cannot rely on the life inherent in the object he imitates, any more than a poet can rely on the life inherent in the words he uses. He has to draw the life forth from within himself.

It is for the same reason that an ever-increasing importance came to be attached to the *invented* image an dmen became more and more dissatisfied with imitations of nature both in the practice and in the theory of art. It is easy to see how it came to be held that ‘the truest poetry is the most feigning’. For there is no boubt about where the life in an invented or fictitious image comes from. There can be no ‘pathetic fallacy’ there. What is peculiar to the Romantic Movement—as, indeed, its very name recalls—is the further reaction of this enthusiasm for fictitious and *fabulous* representations on the phenomena—on Nature herself. This is also what took the Romantic conception of art, properly understood, a step beyond the Neo-platonic theory referred to above. The Neo-platonic theory holds that man the artist is, in come measure, a creator. The Romantic conception agrees—but goes further and returns him, in this capactiy, to Nature herself.

With what result? It is no longer simply that the arts ‘reascend to those principles from which nature herself is derived’. The ‘principles’ themselves have changed their venue. For we are told by the Romantic theory that we must no longer look for the nature-spirits—for the Goddess Natura—on the farther side of the appearances; we must look for them *within ourselves*.

>*Unbewusst der Freuden, die sie schenket,<br/>Nie entzückt von ihrer Herrlichkeit,<br/>Nie gewahr des Geistes, der sie lenket,<br/>Sel’ger nie durch meine Seligkeit,<br/>Fühllos selbst für ihres Künstlers Ehre,<br/>Gleich dem toten Schlag der Pendeluhr,<br/>Dient sie knechtisch dem Gesetz der Schwere,<br/>Die entgötterte Natur.*²

Pan has shut up shop. But he has not retired from business; he has merely gone indoors. Or, in the well-known words of Coleridge:

>*We receive but what we give<br/>And in our life alone does Nature live.*³

It is again beyond the scope of this book to trace in detail the way in which the origin of the Romantic response to nature is exemplified in that association between Coleridge and Wordsworth which gave rise to the *Lyrical Ballads*.  It was the dejected author of the *Ancient Mariner* who grasped the theory; but it was Wordsworth who actually *wrote* the nature-poetry.

If nature is indeed ‘dis-godded’, and yet we again begin to experience her, as Wordsworth did—and as millions have done since his time—no longer is dead but as alive; if there is no ‘represented’ on the far side of the appearances, and yet we begin to experience them once more *as* appearances, as representations—the question arises, of *what* are they representations? It was no doubt the difficulty of answering this quesion which led Wordsworth to relapse occasionally into that nostalgic hankering after *original* participation, which is called pantheism—and from which Coleridge was rendered immune by his acquaintance with Kantian philosophy. We shall find somewhat the same contrast, in this respect, between Goethe and Schiller.

It is because of its failure to answer this question that the true, one might say the tremendous, impulse underlying the Romantic movement has never grown to maturity; and, after adolescence, the alternative to maturity is puerility. There is only one answer to the question. Henceforth, if nature is to be experienced as representation, she will be experienced as representation of—Man. But what is Man? Herein lies the direst possibility inherent in idolatry. It can empty of spirit—it has very nearly succeeded in doing so—not only nature, but also Man himself. For among all the other idols is his own body. And it is part of the creed of idolatry that, when we speak of Man, we mean only the body of this or that man, or at most his finite personaltiy, which we are driven more and more ot think an attribute of his body.

Thus it is, that the great change which the evolution of consciousness has brought about and the great lessons which men had begun to learn have all been wrenched awry. We had come at last to the point of realizing that art can no longer be content with imitating the collective representations, now that these are themselves turning into idols. But, instead of setting out to smash the idols, we have tamely concluded that nothing can now be art which in any way reminds us of nature—and even that practically anything may be art, which does not. We have learned that art can represent nothing but Man himself, and we have interpreted that as meaning that art exists for the purpose of enabling Mr. Smith to ‘express his personality’. And all because we have not learnt—though our very physics shouts it at us—that nature herself is the representation of Man.

Hence the riot of private and personal symbolisms into which both art and poetry have degenerated. If I know that nature herself is the system of my representations, I cannot do otherwise than adopt a humbler and more responsible attitude to the representations of art and the metaphors of poetry. For in the case of nature there is no danger of my fancying that she exists to express my personality. I know in that case that what is meant, when I say she is my representation, is, that I stand, whether I like it or not, in—(I do not love the expression, but I can find no defter one in English) a ‘directionally creator’ relation to her. But I know also that what so stands is not my poor temporal personality, but the Divine Name in the unfathomable depths behind it. And if I strive to produce a work of art, I cannot then do otherwise than strive humbly to create more nearly as *that* creates, and not as my idiosyncrasy wills.

After all, there is warrant for it. At the beginning of the first chapter I pointed to the phenomenon of the rainbow, because it is especially easy there to realize the extent to which it is ‘our’ creation. But we know equally well that it is not only the colours and curve of the rainbow which proceed from the eye; it is not only ‘Iris’ who has gone indoors; we know that light itself–as *light* (whatever we may think about the particles)—proceeds from the same source. Now for the Impressionist painters, this became a real experience. They really painted nature in the light of the eye, as no other painters had done before them. They were striving to realize in consciousness the normally unconscious activity of ‘figuration’ itself. They did not imitate; they expressed ‘themselves’—inasmuch as they painted nature as the representation of Man. They will serve as a reminder—though they are not the only one—that the rejection of original participation may mean, not the destruction but the liberation of images.

>¹ This important little piece of history will be found most effectively summarized at the beginning of Bk. III of Professor C. S. Lewis’s *English Literature in the Sixteenth Century*. Clarendon Press, 1954.

>²From Schiller’s *Die Götter Griechenlands*: ‘Unconscious of the joy she bestows, never transported by her own glory, never aware of the spirit that directs her, never blest through my blessedness, without feeling even for the honour of her artist—as with the dead stroke of a clock’s pendulum she—disgodded Nature—slavishly obeys the law of gravity.’

>³*Ode to Dejection*.
