# XXI<br/>SAVING THE APPEARANCES

It may be well, before proceeding further, to restate very briefly what this book has so far endeavoured to establish. It has been sought to show firstly, that the evolution of nature is correlative to the evolution of consciousness; and, secondly, that the evolution of consciousness hitherto can best be understood as a more or less continuous progress from a vague but immediate awareness of the ‘meaning’ of phenomena towards an increasing preoccupation with the phenomena themselves. The earlier awareness involved expe4riencing the phenomena as representations; the latter preoccupation involves experiencing them, non-representationally, as objects in their own right, existing independently of human consciousness. This latter experience, in its extreme form, I have called *idolatry*.

Idolatry is an ugly and emphatic word and it was deliberately chosen to emphasize certain ugly features, and still more ugly possibilities, inherent in the present situation. Not much has been said of the benefits—not only material ones—which have been conferred on mankind  by this ‘idolatry’ and nothing, as yet, of the supreme benefit, which will be dealt with in the final chapters. As to the former, most people are so well aware of these benefits, and they have been so often and so fully emphasized by others, that I have thought it unnecessary to draw attention to them. But I will mention two at this point. In the first place, together with the ability to experience phenomena as objects independent of human consciousness, there has grown up our enormously improved power of grasping them in exact and quantitative detail. (Indeed, it was by shifting our attention to this detail that we gained that ability.)  With this has come the progressive elimination of those errors and confusions in which alpha-thinking is inevitably entangled while, in its initial stages, it is still overshadowed by participation; that is, the vague but immediate awareness of ‘meaning’ already referred to. And with this again, has come the power of effective manipulation on which our civilization, with its many works of mercy, is based. Surgery, for example, presupposes an acquaintance with the human anatomy exact in the same mode that our knowledge of a machine is exact.

Yet these practical considerations are not the only ones. Along with his idolatry, and because of it, modern man has found the possibility of an entirely new and very charming emotional relation to nature. The devlted love which thousands of naturalists, for example, have felt for some aspect of nature to which they have been drawn, is not in spite of, it is actually *dependent* on their experience of the ‘appearances’ as substantially independent of themselves. The whole joy of it depends on its being an ‘I—it’ relation—oblivious, or contemptuous, of the teleological approach which dominated Aristotle and the Middle Ages. The happy bird-watcher does not say: ‘Let’s go and see what we can learn about ourselves from nature’. He says: ‘Let’s go and see what nature is doing, bless her!’ Without idolatry there would have been no Gilbert White, no Richard Jefferies, no W. H. Hudson, no Lorenz. Nor is this emotional relation confined to the naturalists, professional and amateur. They are merely the most striking example. The possibility of a selfless and attentive love for birds, animals, flowers, clouds, rocks, water, permeates the whole modern mind, its science, its art, its poetry and its daily life. It is something which only a fool would be in a hurry to sacrifice.

On the other hand, precisely if we are *not* fools, our very love of natural phenomena ‘for their own sake’ will be enough to prevent us from hastily turning a blind eye on any new light which can be shed, from any direction whatsoever, on their true nature. Above all will this be the case, if we feel them to be in danger. And if the appearances are, as I have sought to establish, correlative to human consciousness and if human consciousness does not remain unchanged but evolves, then the future of the appearances, that is, of nature herself, must indeed depend on the direction which that evolution takes.

Now in considering future possibilities there are, it has been suggested, two opposing tendencies to be taken into consideration. On the one hand, a further development in the direction, and on the basis, of idolatry; involving in the end the elimination of those last vestiges of original participation, which, as we saw in Chapter XV, survive in our language and therefore in our collective representations. On the other hand, there is the impulse, rudimentary as yet, of teh human imagination to substitute for original participation, a different kind of participation, which I have called ‘final’.  This, we saw, is based on the acceptance (mainly impulsive so far, but occasionally explicit) of the fact that man himself now stands in a ‘directionally creator relation’¹ to the apprarances. It would seem that the appearances are in danger from both quarters, and that they will require ‘saving’, in a rather different sense of the term from that used of old by Simplicius.

The plain fact is, that all the unity and coherence of nature depends on participation of one kind or the other. If therefore man succeeds in eliminating all original participation, without substituting any other, he will have done nothing less than to eliminate all meaning and all coherence from the cosmos. We have seen that here and there he is already beginning an attempt to eliminate meaning—that is, a valid relation to nature—from his language, and therefore with striking a blow at the very roots of his collective representations. Less sensationally, but far more effectively and over a much wider area, his science, with the progressive disappearance of original participation, is losing its grip on any principle of unity pervading nature as a whole and the knowledge of nature. The hypothesis of chance is already crept from the theory of evolution into the theory of the physical foundation of the earth itself; but, more serious perhaps than that, is the rapidly increasing ‘fragmentation of science’ which occasionally attracts the attention of the British Association. There is no ‘science of sciences’; no unity of knowledge. There is only an accelerating increase in that pigeon-holed knowledge by individuals of more and more about less and less, which, if persisted in indefinitely, can only lead mankind into a sort of ‘idiocy’ (in the original sense of the word)—a state of affairs, in which fewer and fewer representations will be collective, and more and more will be private, with the result that there will in the end be no means of communication between one intelligence and another.

The second danger arises from final participation itself. Imagination is not, as some poets have thought, simply synonymous with good. It may be either good or evil. As long as art remained primarily mimetic, the evil which imagination could do was limited by nature. Again, as long as it was treated as an amusement, the evil which it could do was limited in scope. But in an age when the connection between imagination and figuration is beginning to be dimly realized, when the fact of the directionally creator relation is beginning to break through into consciousness, both the good and the evil latent in the working of imagination begin to appear unlimited. We have seen in the Romantic movement an instance of the way in which the making of images may react on the collective representations. It is a fairly rudimentary instance, but even so it has already gone beyond the dreams and responses of a leisured few. The economic and social structure of Switzerland, for example, is noticably affected by its tourist industry, and that is due only in part to increased facilities of travel. It is due not less to the fact that (whatever may be said about their ‘particles’) the *mountains* which twentieth-century man sees are not the mountains which eighteenth-century man saw.

It may be objected that this is a very small matter, and that it will be a long time before the imagination of man substantially alters those appearances of nature with which his figuration supplies him. But then I am taking the long view. Even so, we need not be too confident. Even if the pace of change remained the same, one who is really sensitive to (for example) the differences between the medieval collective representations and our own will be aware that, without travelling any greater distance than we have come since the fourteenth sentury, we could very well move forward into a chaotically empty or a fantastically hideous world. But the pace of change has *not* remained the same. It has accelerated and is accelerating.

We should remember this, when approaching the aberrations of the formally representational arts. Of course, in so far as these are due to affectation, they are of no importance. But in so far as they are genuine, they are genuine because the artist has in some way or other experienced the world he represents. And is so far as they are appreciated, they are appreciated by those who are themselves willing to make a move towards seeing the world in that way, and, ultimately therefore, seeing that kind of world. We should remember this, when we see pictures of a dog with six legs emerging from a vegetable marrow or a woman with a motor-bicycle substituted for her left breast.

The systematic use of imagination, then, will be requisite in the future, not only for the increase of knowledge, but also for saving the appearances from chaos and inanity. Nor need it involve any relinquishment of the ability which we have won to experience and love nature as objective and independent of ourselves. Indeed, it cannot involve that. For any such relinquishment would mean that what was taking place was not an approach towards final participation (which is the proper goal of imagination) but an attempt to revert to original participation (which is the goal of pantheism, of mediumism and much so-called occultism). To be *able* to experience the representations as idols, and then to be able also to perform the act of figuration consciously, so as to experience them as participated; that is imagination.

The extremity of idolatry towards which we are moving renders the attainment of this dual relation to nature a necessity for both art and science. The attempt to unite the voluntary creativity demanded by the one with the passive receptivity demanded by the other is the significance of Goethe’s contribution to the Western mind, as the achievement of it is the significance of Rudolf Steiner’s. It is perhaps still not too late to attend to these portents. The appearances will be ‘saved’ only if, as men approach nearer and nearer to conscious figuration and realize that it is something which may be affected by their choices, the final participation which may be affected by their choices, the final participation which is thus being thrust upon them is exercised with the profoundest sense of responsibility, with the deepest thankfulness and piety towards the world as it was originally given to them in original participation, and with a full understanding of the momentous process of history, as it brings about the emergence of the one from the other.

>¹ Cf. p. 132 
