# IV<br/>PARTICIPATION

In the last few decades this whole question of the figurative make-up of collective representations and theoretical confusion between what I have called figuration and what I have called alpha-thinking has been implicitly raised by certain anthropologists. Putting it in a nutshell, they have suggested, by the whole manner of their approach to the workings of the ‘primitive’ mind, the question: Can there be such a thing as, ‘*They* thought *they* saw?’

Of course, two people can make the same momentary mistake about the identity of an imperfectly seen object. But, as we saw in Chapter II, the generally accepted criterion of the difference between ‘I thought I saw’ and ‘I found it was’ is, that the former is a private, the latter a collective representation. How, then, if the ‘they’ are a whole tribe or population? If the ‘mistake’ is not a momentary but a permanent one? If it is passed down for centuries from generation to generation? If, in fact, it is *never* followed by a ‘they found it was’? The difficulty is, that then the ‘mistake’ is itself a collective representation. And yet for ourselves, as we saw, it is precisely the collectivity of our representations which is the accepted test of their reality. It is this which convinces us that they are *not* mistakes or hallucinations. Why not then also for them—the primative tribe? But this is to go too fast.

The earlier anthropologists assumed as a matter of course that the primitive peoples who still survive in various parts of the earth perceive and think in the same *way* as we do—but that they think incorrectly. The assumption which underlies their whole approach to the subject is effectively epitomized in two sentences from Tylor’s *Primitive Culture*, first published in 1871:

>It was no spontaneous fancy but the reasonable inference that effects are due to causes, which led the rude men of olden days to people with such ethereal phantoms their own houses and haunts and the vast earth and sky beyond. Spirits are personified causes.

This theory of an ‘inferring’ followed by a ‘peopling’, which is usually called ‘animism’, but which Durkheim prefers to call ‘naturism’, is moreover, according to L&#233;vy-Bruhl, especially typical of the English school of anthropology, and he attributes this, rightly or wrongly, to the influence of Herbert Spencer, who assumed so readily that all things evolve from simple to complex. Be that as it may, the theory is attacked by the twentieth-century anthropologists to whom I have referred. They deny the ‘inferring’ and question the ‘peopling’. L&#233;vy-Bruhl himself, for instance, insists, in the light of the evidence, that to ask how the primitive mind would ‘explain’ this or that natural phenomenon is a wrongly formulated question. The explanation is implied in the collective representations themselves. When we find a primitive mind incapable of grasping what is to us the self-evident law of contradiction, it is absurd to imagine such a mind thinking in terms of cause and effect, and of inference from the one to the other, Rather we are in contact with a different kind of thinking and a different kind of perceiving altogether. L&#233;vy-Bruhl describes this ‘prelogical mentality’, which he says is:

>essentially synthetic. By this I mean that the syntheses which compose it do not imply previous analyses of which the result has been registered in definite concepts, as is the case with those in which logical thought operates. In other words, the connecting links of the representations are given, as a rule, in the representations themselves.

This is also found to be a more satisfactory and convincing approach to the phenomenon of totemism, which involves the most inexplicable and, to us, nonsensical identifications and distinctions. To make no class-distinction between the sun and a white cockatoo, but to feel instantly and sharply a world of difference between both of these natural phenomena and a black cockatoo is, it is felt, a state of mind at which it would be difficult to arrive by inference. The elements which the totem-conscious mind selects out of the whole representation for *attention*, are often very very different from those which we select. Often, for instance, it is not much interested in the distinction between animate and inanimate (including artificial) objects.

>Almost everything that we see therein (i.e., in a being or object or natural phenomenon) escapes their attention or is a matter of indifference to them. On the other hand they see many things of which we are unconscious.

This leads L&#233;vy-Bruhl to the conclusion that ‘Primatives see with eyes like ours, but they do not perceive with the same minds’. And he adds:

>It is not correct to maintain, as is frequently done, that primitives associate occult powers, magic properties, a kind of soul or vital principle with all the objects which affect their senses or strike the imagination, and that their perceptions are surcharged with animistic beliefs. It is not a question of *association*. The mustic properties with which things are imbued form an integral part of the idea to the primitive who views it as a synthetic whole. It is at a later stage of social evolution that what we call a natural phenomenon tends to become the sole content of perceptions to the exclusion of other elements which then assume the aspect of beliefs, and finally appear superstitions. But as long as this ‘dissociation’ does not take place, perception remains an undifferentiated whole.

It may be questioned whether the epithet ‘mystic’, as it is used here, and in the expression ‘participation mystique’ which is especially associated with the name of L&#233;vy-Bruhl, adds effectively to his meaning. Elsewhere he has defined the precise significance which he intends by it, and I shall revert to this shortly. What is important is the concept of participation. The principal reason which L&#233;vy-Bruhl, Durkheim and others assign for the fact that primitives ‘do not perceive with the same minds’ as ours, is, that in the act of perception, they are not detached, as we are, from the representations. For us the only connection *of which we are conscious* is the external one through the senses. Not so for them. Thus, for L&#233;vy-Bruhl:

>The collective representations and interconnections which constitute such a (primitive) mentality are governed by the law of participation and in so far they take but little account of the law of contradiction.

He speaks of ‘a veritable symbiosis . . . between the totemic group and its totem’ and tells us that, if we seek to penetrate their mental processes, ‘We must understand “the same” by virtue, not of the law of identity, but of the law of participation’.

Durkheim seeks to carry much further the bearing of anthropological inquiry on the origin and evolution of abstract thought. He affirms, for instance, that the identification of persons and individual phenomena with totems violates the principle of contradiction only as predications¹ does in our own thinking. The root or predecessor of predictions is to be found in ‘the use of totemic emblems by clans to express and communicate collective representations’.

We shall see that this same expression and communication are to-day the function of *language*. ‘Participation’ begins by being an activity, and essentially a communal or social activity. It takes place in rites and initiation ceremonies resulting in

> collective mental states of extreme emotional intensity, in which representation is as yet undifferentiated from the movements and actions which make the communion towards which it tends a reality to the group. Their participation in it is so effectively *lived* that it is not yet properly imagines.

This stage is not only pre-logical, but also pre-mythical. It is anterior to collective representations themselves, as I have been using the term. Thus, the first development Durkheim traces is from symbiosis or active participation (where the individual feels he *is* the totem)² to collective representation of the totemic type (where the individual feels that his ancestors were the totem, that he will be when he dies, etc.). From this symbolic apprehension he then arrives at the duality, with which we are more familiar, of ideas on the one hand and numinous religion on the other.

This extra-sensory participation of the percipient in the representation involves a similar link between the representations themselves, and of course between one percipient and another. ‘Mana’ or ‘waken’ (which *we* can only translate by abstract terms like ‘totemic principle’, ‘life principle’ or—since it is present also in inanimate objests—’being’) is anterior to the individuality of persons and objects; these (says Durkheim) are rather apprehended by the very primitive as ‘stopping-places of mana’. It is, incidentally, here that he finds the prototype of the idea of *force*, which played such a prominent part in the physical science of the nineteenth century. And in emphasizing the ‘religious origin’ of this idea he points out, rather appositly, that Comte regarded the notion of force as a superstition, which was destined to disappear from science—as indeed ht has shown marked signs of doing, since Durkheim’s book was published.

I hope I have not misrepresented either of the two anthropologists from whom I have quoted rather freely. The more so, as I cannot pause to consider the adverse criticism which L&#233;vy-Bruhl in particular has aroused. (I doubt if it was his case that all primitives *invariably* think in a prelogical way. It is certainly not mine.) If I have drawn heavily on these two writers, I have done so by way of illustration rather than argument. It is not very difficult to see what they mean and, by seeing what they mean, the reader may possibly be helped to see what *I* mean.

Collective representations do not imply a collective unity distinct from the individuals comprising the social group. On the other hand their existence does not derive from the individual. In these two respects they may be compared to language. Like the words of a language, they are common to the members of a given social group, and are transmitted from one generation to another, developing and changing only gradually in the process.

Moreover it is impossible to draw a very precise line between representations and beliefs about representations, or, in the terms I have been using, between figuration and alpha-thinking. All collective representations involve figuration and therefore, if figuration is a kind of thinking, involve ‘thought’. But in addition to this nearly all of them involve elements which are actually *apprehended* as thought, or imagined, rather than as perceived. It was this presumably which persuaded L&#233;vy-Bruhl to add the word ‘mystic’ to his ‘participation’. He uses it, he says, ‘in the strictly defined sense in which “mystic” implies belief in forces and influences and actions, which though imperceptible to sense, are nevertheless real’.

When I see a stone fall to the ground, do I ‘believe’ that it is drawn by the force, or the law, of gravity? When I use the telephone, do I ‘believe’ that my correspondent’s voice is recorded and reproduced by an invisible called ‘electricity’? Or are both these thoughts immediately experienced in my representation? Or is one so and not the other? The exact point at which a piece of alpha-thinking has slipped into and become an integral part of the representation is hard to determine and may clearly differ somewhat between individuals of the same social group and for the same individual at different times. It is continually happening, while we are growing up, especially while we are learning to speak. I say I ‘hear a thrush singing outside my window’. But do I? He is invisible, and it might perhaps be a blackbird; I have begun the business of thinking and believing already! The same thing happens to a lifelong birdwatcher. He does no thinking at all. He *recognizes*. He hears a thrush singing. For him alpha-thinking has become figuration.

To sum up what has been said in this chapter: Anthropology began by assuming as a matter of course that primative peoples perceive the same phenomena as we do and on that assumption investigated their beliefs about those phenomens. Now however some anthropologists have begun to point out that the difference between the primitive outlook and ours begins at an earlier stage. It is not only a different alpha-thinking but a different figuration, with which we have to do, and therefore the phenomena are treatedas collective representations produced by that different figuration. It is further maintained by some of them that the most striking difference between primitive figuration and ours is, that the primitive involves ‘participation’; that is, an awareness which we no longer have, of an extra-sensory link between the percipient and the representation. This involves, not only that we think differently, but that the phenomena (collective representation) themselves are different. The first three chapters were devoted to reminding the reader that we do, in fact, still participate in the phenomena, though for the most part we do so unconsciously. *We* can only remind ourselves of that participation by beta-thinking and we forget it again as soon as we leave off. This is the fundamental difference, not only between their thinking and ours, but also between their phenomena and ours. It remains to consider how ours, which are genetically the later, have come to pass.

>The quotations from L&#233;vy-Bruhl in this chapter are mainly to be found in *Le Fonctions Mentales dans les Soci&#233;t&#233;s Inf&#233;rieures (English Translation: *How Natives Think). The quotations from Durkheim are all taken from *The Elementary Forms of the Religious Life*.

>¹*Predication* may be unconventionally, but not really inaccurately, defined as, ‘Whatever is done by the word *is* in such a sentence as: *a horse is an animal;* the earth is a planet’.

>²Anyone who finds it difficult to form any conception of participation, that is, of self and not-self identified in the same moment of experience, should reflect on that whole peculiar realm of semi-subjectivity which still leads a precarious existence under the name of ‘instinct’—or on those ‘irresistable’ impulses, on which psychiatrists are inclined to dwell. Many of us know what panic feels like, and ordinary men are proud of their sexual vigour or ashamed of the lack of it, although the act is readily acknowledged in retrospect to be at least as much something that is done to, or with, them by an invisible force of nature, as something they themselves veritably *do*.
