# VII<br/>APPEARANCE AND HYPOTHESIS

According to Plato there were three stages, or degrees of knowledge. The first and lowest amounted to no more than observation. Since all that we perceive is continually changing, coming into being and passing away, this kind of ‘knowledge’ grasps nothing permanent and nothing therefore which can properly be called ‘truth’. At the opposite pole, the highest degree—which is the only one that can *properly* be called knowledge—is wholly extra-sensory. It is the contemplation by pure intelligence of the divine ideas, and above all of the Supreme Good. The union of these two, that is, of pure intelligence and sense-knowledge, gives rise to an intermediate mental activity, which Plato stigmatized as ‘bastard’—although he insisted on all his pupils studying it as a preparation and a means to the true knowledge. This intermediate activity was geometry; or, as we should now say, mathematics.

These three degrees of knowledge correspond with three different levels of astronomy. The astronomy of observation merely records the movements of the stars, the sun, the moon and the planets, without attempting to account for them or reduce them to any system. From this we can rise to the second astronomy, which seeks to account for the apparently arbitrary movement of, for instance, the planets by supposing regular geometrical patterns to underlie them. By the exercise of this celestial geometry we can render ourselves capable of rising eventually to the third and highest, that is, to the only true knowledge; which is an unobscured participation in the divine Mind, or Word, itself. The real wisdom, as distinct from its not wholly unworthy outcome in the permanent truths of geometry, manifests itself only to him who participates in however slight a degree in the pure and divine Intelligence. This intelligent participation, the privilege of philosophy and in the last resort of initiation, was not mystical. For mystical experience is essentially other than ordinary experience. But the Platonic or Aristotelian participation, which was true knowledge, was simply the half-conscious participation of every man (the participation by virtue of which he *was* a man) cleared of the gross and bewildering mutability which is plastered over it by the other approaqch, through the senses.

Plato further laid it down orally, as we learn from later astronomers, that the science of astronomy proper lay within the middle one of these three spheres of knowledge. In the first place the ‘phaenomena’, or ‘appearances’, that is the apparent movements of the heavenly bodies, could be watched by observation. In the third place the true knowledge, since it was acquainted with the divine spirits who ensouled or guided the heavenly bodies, had already laid down certain fundamental principles. Later on, I shall say something of the ‘mental-spatial’ experience chich claimed to determine the nature of movement out of the nature of pure thought. It appears as a mere confusion to the alpha-thinking of today (although that, too, is beginning to talk without appreciable discomfort of ‘space-time’). Here it must suffice to record that the prescribed movements were, among other requirements, perfect circles at a constant speed.

There is perhaps more of physics than of astronomy in Aristotle’s *De Caelo*, but, as far as the three stages of knowledge and the fundamental principles just referred to are concerned, he was substantially in accord with Plato.

The ‘phenomena’ of which the astronomy of Greece and of the dark and middle ages spoke, were of course not quite what we to-day mean by ‘phenomena’, a word which, outside philosophy, has come to be practically sysnonymous with ‘objects’ and ‘events’. The middle voice of the Greek verb suggests neigher wholly ‘what is perceived, from within themselves, by men’ nor wholly ‘what, from without, forces itself on man’s senses’, but something between the two. This is also fairly suggested by the English word ‘appearances’, which is generally used in translating the once hard-worked phrase *&#963;&#969;&#958;&#949;&#953;&#957; &#964;&#945; &#966;&#945;&#953;&#957;&#959;&#956;&#949;&#957;&#945;*—‘to save the appearances’. This phrase, used by Simplicius in his sixth century *Commentary* on Aristotle’s *De Caelo*, continued to dominate astronomy down to the time of Copernicus.

When we hear of ‘saving appearances’ to-day, we are apt to think of a society hostess at a dinner party where something has gone wrong in the kitchen. It was not so in the seventeenth century. Although he spoke of God’s laughter, Milton was not *himself* laughing at the astronomers when he wrote in the Eighth book of *Paradise Lost*:

>*Or if they list to try<br/>Conjecture, he his fabric of the heavens<br/>Hath left to their disputes, perhaps to move<br/>His laughter at their quaint opinions wide<br/>Hereafter, when they come to model heaven,<br/>And calculate the stars; how they will wield<br/>The mighty frame; how build, unbuild, contrive,<br/>To save appearances; how gird the sphere<br/>With centric and eccentric scribbled o’er,<br/>Cycle and epicycle, orb in orb.*

Nor was he suggesting that desperate expedients were being resorted to, in order to ‘save’ (in the sense of rescuing) the Ptolemaic system—which, incidentally, he had made the framework of his own poem. He was introducing a learned *clich&#233;*.

The same passage from Simplicius contains the Greek verb from which we derive the word ‘hypothesis’. The spheres and orbits by which the appearances were to be saved were normally ‘hypotheses’ in the strict sense of the word, that is, assumptions made for the purpose of a particular argument and by the same token not posited as true. A brief digression on the almost lost distinction between the word ‘hypothesis’ and the word ‘theory’ may not be amiss here. The Greek word *&#952;&#949;&#969;&#961;&#953;&#945;* (theoria) meant ‘contemplation’ and is the term used in Aristotle’s psychology to designate the moment of fully conscious participation, in which the soul’d *potential* knowledge (its ordinary state) becomes *actual*, so that man can at last claim to be ‘awake’. This is no guide to its present, or even recent meaning, but it does emphasize the difference between a proposition which it is hoped may turn out to be true, and a proposition, the truth or untruth of which is irrelevant. The geometrical paths and movements devised for the planets were, in the minds of those who invented them, *hypotheses* in the latter sense. They were arrangements—devices—for saving the appearances; and the Greek and medieval astronomers were not at all disturbed by the fact that the same appearances could be saved by two or more quite differenet hypotheses, such as an eccentric or an epicycle or, particularly in the case of Venus and Mercury, by supposed revolution round the earth or supposed revolution round the sun. All that mattered was, which was the simplest and the most convenient for practical purposes; for neither of them had any essential part in truth or knowledge.

Unless we realize, with the help of a little historical excavation of this kind, what from the epistemological point of view astronomy then signified and had signified for about two thousand years, we shall not understand the real signicance of Copernicus and Galileo. The popular view is, that Copernicus ‘discovered’ that the earth moves round the sun. Actually the *hypothesis* that the earth revolves round the sun is at least as old as the third century B.C., when it was advanced by Aristarchus of Samos, and he was neither the only, nor probably the first astronomer to think of it. Copernicus himself knew this. Secondly it is generally believed that the Church tried to keep the discovery dark. Actually Copernicus did not himself want to publish his *De Revoolutionibus Orbium*, and was only eventually prevailed on to do so by the importunity of two eminent Churchmen.

The real turning-point in the history of astronomy and of science in general was something else altogether. It took place when Copernicus (probably—it cannot be regarded as certain) began to think, and others, like Kepler and Galileo, began to affirm that the heliocentric hypothesis not only saved the appearances, but was physically true. It was this, this novel idea that the Copernican (and therefore any other) hypothesis might not be a hypothesis at all but the ultimate truth, that was almost enough in itself to constitute the ‘scientific revolution’, of which Professor Butterfield has written:

>it outshines everything since the rise of Christianity and reduces the Renaissance and Reformation to the rank of mere episodes, mere internal displacements, within the system of medieval Christendom.¹

When the ordinary man hears that the Church told Galileo that he might teach Copernicanism as a hypothesis which saved all the celestial phenomena satisfactorily, but ‘not as being the truth’, he laughs. But this was really how Ptolemaic astronomy had been taught! In its actual place in history it was not a casuistical quibble; it was the refusal (unjustified it may be) to allow the introduction of a new and momentous doctrine. It was not simply a new theory of the nature of the celestial movements that was feared, but a new theory of the nature of theory; namely, that, if a hypothesis saves all the appearances, it is identical with truth.²
them the last traces of original participation. In doing so he has produced the mechanomorphic collective representations which constitute the Western World today.

>The reader who wishes to verify, or investigate further, the arguments of this Chapter, should consult P. Duhem’s *Le Syst&#233;me du Monde. Histoire du doctrines cosmologiques de Platos &#224; Copernic*. Paris 1913-17. This monumental work, which combines German thoroughness with French lucidity, was unfortunately never finished. The author had completed fove (out of, I believe, eight) volumes before his death. The latest part of the period defined in the sub-title is, however, covered briefly in a series of articles by Duhem printed in *Annales de Ph&#237;loloph&#237;e Chr&#233;tienne (Apl.-Sept. 1908) under the title &#931;&#969;&#958;&#949;&#953;&#957; &#964;&#945; &#966;&#945;&#953;&#957;&#959;&#956;&#949;&#957;&#945;. Essai sur la Notion de Th&#233;orie Physique de Platon&#224; Galil&#233;e.*

>*Le Syst&#233;me du Monde* also gives a full historical account of refinements into which it would have been disproportionate for me to enter, such as the opposition of the more literal-minded Arabian astronomers to the Ptolemaic hypotheses (on the ground of their incompatibility with *Aristotelian* physics) and the epistemological distinction, at one time sharply emphasized, between the subject-matter of physics (sublunary phenomena) and astronomy (celestial phenomena).

>See also *Aquinas and Kant* by Gavin Ardley. Longmans Green & Co. 1950.

>¹*Origins of Modern Science*. Bell. 1949. Macmillan. 1941

>²Cr. Aquinas, *Summa*, 12. Qu. 32. 3. 1 ad 2. The other view was assumed by Ptolemy himself (*Almagest*, Bk. III, chaps. ii and iv; Bk. XIII, chap. ii). In the time of Copernicus it was still the official view, though not undisputed. See also Note at the end of this Chapter.
