# II<br/>COLLECTIVE REPRESENTATIONS

A representation is something I perceive to be there. By premising that the everyday world is a system of collective representations, it may be thought that we blur the distinction between the fancied and the actual or, following the everyday use of language, between the apparently there and the really there. But this is not so. It only seems to be so because of the very great emphasis which—especially in the last three or four hundred years—the Western Mind has come to lay on the ingredient of spatial depth in the total complex of its perception. I shall return to this later.

As to what is meant by ‘collective’—any discrepancy between my representations and those of my fellow men raises a presumption of unreality and calls for explanation. If, however, the explanation is satisfactory; if, for instance, it turns out that the discrepancy was due, not to my hallucination, but to their myopia or their dullness, it is likely to be accepted; and then my representation may itself end by becoming collective.

It is, however, not necessary to maintain that collectivity is the *only* test for distinguishing between a representation and a collective representation (though, to creatures for whom insanity is round the corner, it is often likely to be the crucial one).

I am hit violently on the head and, in the same moment, perceive a bright light to be there. Later on I reflect that the light was ‘not really there’, even if I had lived all my life on a desert island where there was no-one to compare notes with, I might do as much. No doubt I should learn by experience to distinguish the first kind of light from the more practicable light of day or the thunderbolt, and should soon give up hitting myself on the head at sunset when I needed light to go on working by. In both cases I perceive light, but the various criteria of difference between them—duration, for instance, and a sharp physical pain, which the one involves and the other does not, are not difficult to apprehend.

What is required, is not to go on stressing the resemblance between collective representations and private representations, but to remember, when we leave the world of everyday for the discipline of any strict inquiry, that, *if* the particles, or the unrepresented, are in fact all that is *independently* there, then the world we all accept as real is in fact a system of collective representations.

Perception takes place by means of sense-organs, though the ingredient in it of sensation, experienced as such, varies greatly as between the different senses. In touch I suppose we come nearest to sensation without perception; in sight to perception without sensation. But the two most important things to remember about perception are these: *first*, that we must not confuse the percept with its cause. I do not hear undulating molecules of air; the name of what I hear is *sound*. I do not touch a moving system of waves or of atoms and electrons with relatively vast empty spaces between them; the name of what I touch is *matter*. *Second*, I do not perceive any *thing* with my sense-organs alone, but with a great part of my whole human being. Thus, I may say, loosely, that I ‘hear a thrush singing’. But in strict truth all that I ever merely ‘hear’—all that I ever hear simply by virtue of having ears—*is sound*. When ‘I hear a thrush singing’, I am hearing, not with my ears alone, but with all sorts of other things like mental habits, memory, imagination, feeling and (to the extent at least that the act of attention involves it) will. Of a man who merely heard in the first sense, it could meaningfully be said that ‘having ears’ (i.e., not being deaf) ‘he heard not’.

I do not think either of these two maxims depends on any particular theory of the nature of perception. They are true for any theory of perception I have ever heard of—with the possible exception of Bishop Berkeley’s. They are true, whether we accept the Aristotelian and medieval conception of form and matter, or the Kantian doctrine of the forms of perception, or the theory of specific sense-energy, or the ‘primary imagination’ of Coleridge, or the phenomenology that underlies Existentialism, or some wholly unphilosophical system of physiology and psychology. On almost any received theory of perception the familiar world—that is, the world which is apprehended, not through instruments and inference, but simply—is for the most part dependent upon the percipient.
