# XXIII<br/>RELIGION

When one ventures to speak, as I did in Chapter XIX, of man standing ‘in a directionally creator relation’ to the phenomena, it is clear that a theological issue is raised. Religion is essentially an ‘I-Thou’ relation between man on the one hand and the Creator of man and of his phenomena, on the other. A man who cannot think of his Creator as a Being other than himself cannot be said to have a religion. This is a truth of which modern theology, in its reaction against the vague creative-evolutionism, which sometimes passed muster as religion in the nineteenth century, is very much and very healthily aware.

Unfortunately, it is just on the interpretation and application of this all-important truth that our modern idolatry has fastened its claws. For idolatry has coarsened the very meaning of ‘otherness’—the very way in which ‘other’ and ‘same’ can be thought. We have seen, in Chapter XIII, how distinctions not determined by the senses were once concrete experiences, before they faded away into the ‘frigidity’ of subjective ideas with the coming of the scientific revolution. We have seen, for instance, how Schiller was unable to conceive that Goethe’s *Urphänomen* could be anything at all, unless it was *either* a phenomenon perceivable by the passive senses, *or* an abstract idea. So to the typical modern mind, fixed firm in its idolatry, unless God is thought of as not merely other than itself, but other *in the phenomenal mode* and after the manner in which the idols ore other, God must be merely an idea.

Yet this can be no more than a passing blindness. Once it was remembered, and some day it will be realized afresh, that ‘the soul is in a manner all things’, God the Father is not less, but *more* ‘other’ from me than are the phenomena. But, if I think of Him as other *in the same mode* as the phenomena, then I substitute an idol for Him; and if I then proceed to worship Him so thought of, then, whatever I may *say* about it, in the secret recesses of my soul I am worshipping—perhaps some kind of guardian angel, certainly not my Creator. In order to be sure of distinguishing him numerically from myself, and in the name of humility, I have dared to think of him as an existence *parallel* with my own. Herein lies the idolatry which infects contemporary religion.

We saw, in Chapter XVI, how the willed ousting of participation, which was the paramount impulse, or obedience, of the Jews, could contribute to the same result as did the alpha-thinking of the Greeks and their successors. But we saw also how a waxing experience of the *inwardness* of the Divine Name was the proper counter-pole to their loss of original participation. We stopped short, however, of the point where this experience was lost. By the time Jesus was born the Divine Name had ceased to be spoken by man in the Temple or elsewhere. The pharisees had made it the name of a Being essentially objective, remote, inaccessible, infinitely superior to, yet imagined as existentially parallel with man. Thus, the Jews had barely glimpsed, before they again lost sight of, that which is the opposite pole to man’s otherness from the I AM, namely his supreme identity with it.

The fixing of such a gulf between God and man was not fatal to religion so long as some measure of original participation remained. To a participating consciousness, apprehending the world and the word as image, many nouns are the names of the Creator (‘non proprie sed per similitudinem’) and the noun *God* is merely one of them. To a non-participating consciousness, apprehending the world as object, most nouns are the names of idols and the noun *God* can be no exception.¹ If the noun *God* were indeed the Divine Name, it would not frequently appear in discourse as the subject of easy and familiar sentences. Whereas, in fact, it is long now since this liberty became almost the recognized mark by which we distinguish the sermon from other forms of utterance. The progressive loss of original participation necessarily involves one of two alternatives, *either* an ever-increasing experience of the inwardness of the Divine Name and the Divine Presence—which is the religious aspect of what I have called ‘final participation’—o*or*an ever-increasing idolatry, in religion as elsewhere.

This dilemma I believe to be the ultimate and innermost significance of Protestantism, the development of which has been roughly contemporary with that of the scientific revolution. For the idolatry of which I have just written is, of course, not the whole story. In many corners, in many movements, both within and without the established churches, a new impulse towards final participation has gathered strength, as men have attempted to make the Pauline maxim: ‘Not I, but Christ in me’ a living experience. ‘Though God be everywhere present,’ wrote William Law (author of the ‘Serious Call’);

>yet He is only present to thee in the deepest and most central part of thy soul. Thy natural senses cannot possess God, or unite thee to Him; nay, thy inward faculties of Understanding, Will and Memory can only reach after God, but cannot be the place of His habitation in thee. But there is a root or depth in thee, from whence all these faculties come forth, as lines from a centre, or as branches from the body of the tree. This depth is called the Centre, the Fund or Bottom of the soul. This depth is the Unity, the Eternity, I had almost said the Infinity of thy soul; for it is so infinite that nothing can satisfy it, or give it any rest but the infinity of God.²

This, on the one side, and oh the other that valiant attempt, which began with the Reformation and ended in Fundamentalism, to understand and accept literally—*and only literally*—the words of the Bible, precisely while their meanings were being subtly drained away by idolatry—these are the opposite and complimentary poles between which Protestantism has hitherto revolved.

If this book has succeeded in showing anything, it has shown that the only possible answer to the idolatry with which all our thinking is to-day infected, is the acceptance and conscious ensuing of that directionally creator relation to the phenomenal world, which we know to be a fact, whether we like it or not. Is God’s creation less awe-inspiring because I know that the light, for instance, out of which its visual substance is woven, streams forth from my own eyes? ‘Look upon the rainbow,’ wrote the author of *Ecclesiasticus*:

>Look upon the rainbow, and praise him who made it:<br/>Very beautiful it is in the brightness thereof.

>It compasseth the heavens about with a glorious circle<br/>and the hands of the most High have bended it.

Do I echo these words less warmly, when I recollect that יהוה is creating the rainbow through my eyes? When I know that to think otherwise is an illusion or a pretence? Does piety depend on original participation? If so, one thing is certain; there is no future for it. But fortunately it does not. I did not create my eyes. And if an understanding of the manner of my participation in the appearance of a rainbow does not diminish my awe before its Creator, why should that be the case with the other more palpable phenomena? What but idolatry could ever make me suppose it *was* the case? ‘Let not your heart be troubled: you believe in God, believe also in me.’

I did not create my eyes. But we saw at the beginning of this book how, in order that the world of appearances may arise, it is not enough for the senses alone to be added to the unrepresented. That world depends no less on man’s figuration; and, with that, also on his imagination. It is because imagination participates the creative activity in this way that it has itself been dimly felt to be, and described as, ‘creative’. We saw in Chapter XXI how this means that the future of the phenomenal world can no longer be regarded as entirely independent of man’s volition. This is the difference between original and final participation.

This is also a conclusion from which piety may shrink. We must then ask ourselves (apart altogether from our obligation to accept the truth because it is true) whether we *ought* to shrink from the notion that we are to share the responsibility of maintaining an earth which it has already, it seems, been given into our hands to destroy. Moreover, has history any real significance unless, in the course o fit, the relation between creature and Creator is being changed?

>God’s view is the view of mind as such, for it corresponds to the real structure of existence. The tendency of any mind, in proportion as it overcomes its creaturely limitations, must be to gravitate towards the divine centre, and share the divine view of things. That is the goal; it cannot be the starting-point.³

Has history any significance, unless we can apply these words to the whole development of the mind of man? Would it not be wiser, instead of shrinking, to recall the words of St. Paul: *For the earnest expectation of the creature waiteth for the manifestation of the sons of God*—and the German poet, Novalis’s gloss: *Man is the Messiah of nature?*

On the other hand, it may be objected that all this talk of the relation of man to the phenomenal world is cold stuff, having little or nothing to do with religion, whose field is the soul and its salvation. But this ‘watertight’ attitude is itself a product of idolatry. What the Psalmist wrote of the old idols is true no less of the idols of the twentieth century. ‘They that make them are like unto them.’ The soul is in a manner all things, and the idols we create are built into the souls of our children; who learn more and more to think of themselves as objects among objects; who grow hollower and hollower. In the long run we shall not be able to save souls without saving the appearances, and it is an error fraught with the most terrible consequences to imagine that we shall.

Let us not, nevertheless, be unduly oppressed by the fear of losing all we are accustomed to, whether it be that delight in a wholly independent world of nature of which I spoke in Chapter XXI, or of some special brand of piety that depends on it. but let us make no mistake as to the magnitude of the moral demand which is made on us. In that respect there is no need for the moralist to worry. It is not such cold stuff after all. The world of final participation will one day sparkle in the light of the eye as it never yet sparkled early one morning in the original light of the sun. But the coming of this light presupposes a goodness of heart and a steady furnace in the will, which have only not been emphasized in this book, because they are not the subject of it.

The morality of imagination is subtle and deep and far-reaching—subtle above all, because imagination itself is still in its tender infancy. I have already pointed out that imagination and goodness are *not* synonymous. But I believe that, if we are sensitive to it, we may divine in this age a very close and special relation between them. This relation was the guiding intuition of that great, confused spirit—the very St. George of iconoclasm—William Blake, who held that Imagination is the cardinal virtue, because the literalness which supports idolatry is the besetting sin, of the age which is upon us. But we must walk warily here.

It is in the nature of the case that, if at any point in time something like a *new* moral demand is made on humanity, moral judgments grow for a time double and confused. Thus, in Chapter XIX I spoke of certain ‘symptoms of iconoclasm’, in the shape of a new willingness to apprehend symbolically. If I now maintain that these have a moral significance, and indeed a paramount moral significance, I am at once in the difficulty that the scale of values I have set up not only does not correspond with the generally accepted scale of Christian moral values, but appears to cut right across it. There are plenty of people with a natural taset for dream-psychology, or for art or literature of a symbolical nature, for sacramentalism in religion, or for other things whose meaning cannot be grasped without a movement of the imagination, who are arrogant or self-centered or in other ways no better than they should be. And conversely there are prosaic, humdrum, literal souls before whose courage and goodness we are abashed. It is not a happy task to have to maintain that, from one point of view, and that an all-important one, the former must be accounted morally superior. But then neither would it have been a happy task to have to maintain, let us say, to a disciple of Rabbi Hillel, that from one point of view and that an all-important one, some of the more raffish members of St. Paul’s congregation at Corinth possessed the one thing needful which the Rabbi lacked. The ‘needful’ virtue is that which combats the besetting sin. And the besetting sin to-day is the sin of literalness,⁴ or idolatry. Relative moral values are not as simple as relative places in class at school. There is a tragedy of progress.

And yet in neither case, perhaps, to a fine and sincere moral intuition, is the apparent irrelevance as total as I have just suggested. The relation between the mind and heart of man is a delicate mystery, and hardness is catching. It will, I believe, be found that there *is* a valid connection, at some level however deep, between what I have called ‘literalness’ and a certain hardness of heart. Listen attentively to the response of a dull or literal mind to what insistently presents itself as allegory or symbol, and you may detect a certain irritation, a faint, incipient aggressiveness in its refusal. Here I think is a deep-down moral gesture. You may, for instance, hear the literal man object suspiciously that he is being ‘got at’ by his unconscious through the symbolism of his dreams. An attempt is being made, of which he is dimly aware, to undermine his idols, and his feet are being invited on to the beginning of the long road, which in the end must lead him to self-knowledge, with all the unacceptable humiliations which that involves. Instinctively he does not like it. He prefers to remain ‘literal’. But of course he hardly knows that he prefers it, since self-knowledge is the very thing which he is avoiding.

We could pursue the matter further and instance, on the positive side, a certain humble, tender *receptiveness* of heart which is nourished by a deep and deepening imagination and by the self-knowledge which that inevitably involves. Perhaps this is what Blake had in mind, when he called Imagination ‘the Divine Body of the Lord Jesus, blessed for ever’; but we have digressed too far already from the main road.

One final word, however, before we leave the specifically moral aspect behind us. It may be objected that however true it may be, all that I have been saying is much too difficult to have much to do with the religion of ordinary men. This is not an objection which would have appealed to St. Augustine or the Fathers of the Church, but let us consider it. In the first place, a great deal of the complexity of my argument is due to the deep-seated error, with its consequently innumerable ramifications, which that argument has sought to unravel. The movements of fingers disentangling a crumpled skein are complicated, but the final result is not complication. Secondly, from one point of view God is always simple, as the light is simple, and the simplest soul can turn to Him at whatever point it stands in the matter of education or wisdom. But from another, since He is everywhere present, He must be at least as complicated as the most complicated thing in His creation. God’s view is ‘the view of mind as such’—and outside idolatry we cannot really separate His ‘view’ of creation from creation itself—except as the Persons of the Trinity are ‘separate’.

There is, moreover, a topical application of this truth. In the industrial and urbanized civilization of to-day many of the ‘simple’ minds which meet with indifference or with indignant protest any suggestion of difficulty or complexity in theology, are not so simple when it comes to tackling the complexities of the phenomenal world in nature or machinery. The relation between the mind and heart of man is indeed a close and delicate one and any substantial cleft between the two is unhealthy and cannot long endure. Hence, however the case may stand for the time being, or with a few individuals here and there, it is certain that the mind of man as a whole cannot safely be left to occupy itself with idols, while a moral, or even an adoring ‘ghost in the machine’ responds to the otherness of God with love and obedience and the cultivation of self-improvement.

There will be a revival of Christianity when it becomes impossible to write a popular manual of science without referring to the incarnation of the Word. It is these books, not popular theolgy (however excellently and simply it is written, as to-day it often is) on which the mind of the proletariat seizes as it awakens from its ancient peasant-dreaming and peasant-wisdom. It is these—especially if they are laced with Marxism—which the needy oriental student in Bloomsbury devours and takes home with him; it is these which up to now are the answering legacy of the West to the East, whence she once derived her religion. The hungry sheep look up and are not fed. But Marxism forges ahead, because the scientific outlook (which is in the blood of the proletariat, because it is in the collective representations to which they are awakening) is part and parcel of its message; whereas to Christian doctrine, as now presented, it is at worst a stumbling-block and, at best, totally irrelevant.

I have tried to show in this book that it is in fact very far from irrelevant; inasmuch as the scientific revolution marked a crucial stage in that evolution from original to final participation, which is the progressive incarnation of the Word. I have tried to show that the phenomena cannot be understood in their true nature without an understanding of precisely that evolution.

In a letter to *The Times* last year, concerning the evangelical mission of Dr. Graham, the Bishop of Plymouth wrote:

>. . . Our Lord constantly emphasized his healing ministry to the whole man; if he is not Lord of our minds, he is not the saviour whom this generation, which is our immediate concern, so sorely needs.

I am persuaded that in our time the battle between the powers of good and evil is pitched in man’s mind even more than in his heart, since it is known that the latter will ultimately follow the former. In the Christian doctrine of the Trinity the Logos, or Word, is one of the three Persons. The conception of a threefold nature in the Godhead is not, however, peculiar to Christianity. It is to be found also in oriental religions and is perhaps the formal principle underlying the whole complicated organism of Greek mythology. It is the *depth* of all theology. What is peculiar to Christianity is the nexus which that acknowledges between the Second Person of the Trinity and a certain historical *event in time*. For the Christian, accordingly, religion can never be simply the direct relation between his individual soul and the eternal Trinity. As long as we ourselves are occupying a standpoint in time, so long, interposed between the First and Third Persons, all history, in a manner, lies.

Not to realize to the uttermost the otherness of God from ourselves is to deny the Father. But equally, not to strive to realize the sameness—to renege from the Supreme Identity—is to deny the Holy Spirit. This, any deeply religious man may feel, whatever terminology he may have learnt to employ. To this a true Christian—or so it seems to me—must add: In no way to relate the former with the past, and the latter with the future of the world, is to seek to deprive history, and perhaps time itself, of all religious significance.

>¹Cf. Aquinas. *Summa* Ia, qu. 13, a 9.

>²*The Spirit of Prayer*, Part I, ch. 2.

>³Austin Farrer, *A rebirth of Images*, Dacre Press. 1949

>⁴It is at this point that I can most happily acknowledge the very real debt which my book owes to stimulus and enlightenment derived from the conversation and writings of my friend Mr. Roger Home. Indeed the recollection of his *saeva indignatio* on the subject of ‘literalness’ may well have been the catalyst, without which a rather wayward collection of notes and ideas would never have taken shape as a book at all.
