# I<br/>THE RAINBOW

Look at a rainbow. While it lasts, it is, or appears to be, a great arc of many colors occupying a position out there in space. It touches the horizon between that chimney and that tree; a line drawn from the sun behind you and passing through your head would pierce the centre of the circle of which it is part. And now, before it fades, recollect all you have ever been told about the rainbow and its causes, and ask yourself the question *Is it really there?*

You know, from memory, that if there were a hillside three or four miles nearer than the present horizon, The rainbow would come to earth in front of and not behind it; that, if you walk to the place where the rainbow ends, or seems to end, it would certainly not be ‘there’. In a word, reflection will assure you that the rainbow is the outcome of the sun, the raindrops and your own vision.

When I ask of an intelligible appearance or representation, Is it really there? I usually mean, Is it there independently of my vision? Would it still be there, for instance, if I shut my eyes—if I moved towards or away from it. If this is what you also mean by ‘really there’, you will be tempted to add that the raindrops and the sun are really there, but the rainbow is not.

Does it follow that, as soon as anybody sees a rainbow, there ‘is’ one, or, in other words, that there is no difference between an hallucination or a madman’s dream of a rainbow (perhaps on a clear day) and an actual rainbow? Certainly not. You were not the only one to see that rainbow. You had a friend with you. (I forbear asking if you both saw ‘the same’ rainbow, because this is a book about history rather than metaphysics, and these introductory chapters are merely intended to clear away certain misconceptions.) Moreover, through the medium of language, you are well aware that thousands of others have seen rainbows in showery weather; but you have never heard of any sane person claiming to have seen one on a sunless or a cloudless day. Therefore, if a man tells you he sees a rainbow on a cloudless day, then, even if you are convinced that he means what he says, and is not simply lying, you will confidently affirm that the rainbow he sees is ‘not there’.

In short, as far as being really there or not is concerned, the practical difference between a dream or hallucination of a rainbow and an actual rainbow is that, although each is a  representation or appearance (that is, something which I perceive to be there), the second is a *shared* or collective representation.

Now look at a tree. It is very different from a rainbow. If you approach it, it will still be ‘there’. Moreover, in this case, you can do more than look at it. You can hear the noise its leaves make in the wind. You can perhaps smell it. You can certainly touch it. Your senses combine to assure you that it is composed of what is called solid matter. Accord to the tree the same treatment that you accorded to the rainbow. Recollect all you have been told about matter and its ultimate structure and ask yourself if the tree is ‘really there’. I am far from affirming dogmatically that the atoms, electrons, nuclei, etc., of which wood, and all matter, is said to be composed, are particular and identifiable objects like drops of rain. But if the ‘particles’ (as I will here call them for convenience) *are* there, and are all that is there, then, since the ‘particles’ are no more like the thing I call a rainbow, it follows, I think, that—just as a rainbow is the outcome of the raindrops and my vision—so, a tree is the outcome of the particles and my vision and my other sense-perceptions. Whatever the particles themselves may be thought to be, the tree, as such, is a representation. And the difference, for me, between a tree and a complete hallucination of a tree is the same as the difference between a rainbow and an hallucination of a rainbow. In other words, a tree which is ‘really there’ is a collective representation. The fact that a dream tree differs in kind from a real tree, and that it is just silly to try and mix them up, is indeed rather literally a matter of ‘common sense’.

This background of particles is of course presumed in the case of raindrops themselves, no less than in that of trees. The relation, *raindrops: rainbows*, is a picture or analogy, not an instance, of the relation, *particles: representation*.

Or again, if anyone likes to press the argument still further and maintain that what is true of the drops must also be true of the particles themselves, and that there is ‘no such thing as an extra-mental reality’, I shall not quarrel with him, but I shall leave him severely alone; because, as I say, this is not a book about metaphysics, and I have no desire to demonstrate that trees or rainbows—or particles—are not ‘really there’—a proposition which perhaps has not much meaning. This book is not being written because the author desires to put forward a theory of perception, but because it seems to him that certain wide consequences flowing from the hastily expanded sciences of the nineteenth and twentieth centuries, and in particular their physics, have not been sufficiently considered in building up the general twentieth-century picture of the nature of the universe and of the history of the earth and man.

A better term than ‘particles’ would possibly be ‘the unrepresented’, since anything particular which amounts to a representation will always attract further physical analysis. Moreover, the atoms, protons and electrons of modern physics are now perhaps more generally regarded, not as particles, but as notional models or symbols of an unknown supersensible or subsensible base. All I seek to establish in these opening paragraphs is, that, whatever may be thought about the ‘unrepresented’ background of our perceptions, the *familiar* world which we see and know around us—the blue sky with white clouds in it, the noise of a waterfall or a motor-bus, the shapes of flowers and their scent, the gesture and utterance of animals and the faces of our friends—the world too, which (apart from the special inquiry of physics) experts of all kinds methodically investigate—is a system of collective representations. The time comes when one must either accept this as the truth about the world or reject the theories of physics as an elaborate delusion. We cannot have it both ways.
