# XV<br/>GRAECO-ROMAN AGE (MIND AND MOTION)

Earlier in this book, and particularly in Chapter X, attention was drawn to the difference between a history of thought or of ideas, on the one hand, and a history of consciousness on the other. I am of course aware that the various expressions of medieval thought which I have discussed in the last two chapters are usually explained in quite a different way. Where I have treated them as arising out of, and betokening, a slightly different relation between the mind of man and his phenomena—and that itself as implying slightly different phenomena—the ordinary view regards them purely and simply as a different ideology superimposed on phenomena which were in all respects the same as our own. By tracing this ideology through a chain of individual thinkers—Plato, Aristotle, the Neo-Platonists, Galen, Isidore of Seville, Vincent de Beauvais, Martanus Capella and others—the medieval outlook is presented as a stage in the history of (largely erroneous) ideas.

Now one outstanding thinker does, of course, pass on his ideas to others, and especially so in an age when books are few and hard to come by. There is, therefore, also a valid and significant history of ideas as such. But the irreconcilable conflict between the two approaches—if what we are seeking is a fundamentally *adequate* history of the human mind—becomes especially apparent when we look back, as I endeavoured to do in the last chapter, on the ideas which the Western mind has formed in the past about this very question, of its own relation to the phenomena, or in other words, when we survey its theories of knowledge. We must, then, make our choice. The whole basis of epistemology from Aristotle to Aquinas assumed participation, and the problem was merely the precise manner in which that participation operated. We can either conclude that this persistent assumption was a piece of elaborate self-deception, which just happened to last, not only from Aristotle but from the beginnings of human thought down to the fifteenth or sisteenth century A.S., or we can assume that there really was participation. I should find the second hypothesis the less fantasatic of the two, even if it were not necessary, on the other and quite unhistorical grounds (as I have suggested that it is), to accept participation as the permanent ground of our collective representations.

It is to me rather too flattering a view to take of the philosophers, not excepting even Aristotle, to regard them as the efficient and sufficient causes of collective representations shared by the greater part of Western Humanity for nearly twenty centuries. From the point of view of a history of consciousness, their writings are rather landmarks to indicate the nature of that consciousness, inasmuch as they represent the human mind in its most wakeful state. At the same time, owing to the subtle link between thinking and figuration, and to the part played by language in evoking and sustaining the collective representations, they are by no means without causal significance. On either view, whether we choose to treat the history of the mind as a history of ideology or as a history of consciousness, we shall find that the continuity between Greek and medieval epistemology is far more striking than the break; and again, on either view, the language and the thought of Plato and Aristotle are the twin strands about which that continuity clusters.

For the history of the mind—above all, when it is treated as a history of consciousness—the periods into which it is most convenient and most significant to divide the past history of mankind, will not be those familiar ones which are adapted to a more superficial record. From the former point of view, the Graeco-Roman period is seen as extending, practically unbroken, to the end of the Middle Ages. And beyond it; for the scientific revolution took some three or four centuries to accomplish completely, and participation died not suddenly but by inches. It survived, for example, in chemistry longer than in the other sciences and, after it had vanished altogether, not only from the sciences but from the collective representations of the educated, or at least the urbanized part of mankind, its echo continued to survive in their habitual use of language for the purposes of thought. It is indeed only in our own time that we are witnessing its eviction from that final stronghold.

We have already seen that logical predication was based by Aquinas on participation. Is it not apparent to reflection, that the validity of alpha-thinking, in so far as it is based on logic, rests on that very participation which it tends, by its operation, to destroy? We can continue to apprehend phenomena as participating one another, in a way which renders logical predication meaningful, only as long as we continue to apprehend them as participated by ourselves. When that ceases, they become idols, and idols do not participate one another. Nor are they connected in any necessary way with their *names*. They are simply ‘there’. Accordingly, the names cannot meaningfully be predicated of each other. In the logic of, for instance, John Stuart Mill, a certain residue of participation is still tacitly assumed. Where that has finally vanished and idolatry is total, *species*, *genus* and the rest of them vanish, as realities. Thus, early in the twentieth century, formal logic begins to boggle much more heavily at the notion of predication, and really to *feel* the difficulty of distinguishing it from an assertion of numerical identity. Sooner or later a Wittgenstein or an Ayer inevitably arises, convinced that all predication must be either false or tautologous—a state of mind which was playfully foreshadowed by Plato more than two thousand years ago in his dialogue, *The Sophist*. to this point of view, the belief that in the act of predication the mind is operating, not only on words but on things themselves, can only appear as a kind of survival of totemism. And that is indeed what it is, if for ‘totemism’ we substitute ‘participation’.¹

The aim of the three preceding chapters was, to characterize the collective representations of the period immediately preceding the scientific revolution, in the particular respect in which they differed most from our own. They were mainly illustrated from the close of that period in what are called the Middle Ages; but most of what was said applies with equal or greater force to the Graeco-Roman age proper, in which the period began. As far as participation is concerned, the difference between medieval and Greek thought is one of degree rather than of kind; and I shall limit myself to a very few observations on the latter. In the first place, there are strong indications in the Greek language and elsewhere, apart altogether from philosophy, that the participation of the ordinary man was a livelier and more immediate experience. The gods and nature-spirits of Greek mythology, and, in particular, the whole Dionysian element in the cults, linked man and nature in a unity which for a very good reason could not, as we shall see, and did not survive the impact of Christianity. But apart from religion, if we were attentive to the *nuances* of the Greek language, we shall find many signs of a living participation in nature—expecially perhaps the nature of man’s own bodily processes—of which we to-day know next to nothing. I feel, moreover, that the superlative quality of Greek sculpture at its height must be attributed to that participation, rather than to any mere excellence in the craft of meticulous imitation.

At the philosophical level, we may reflect from this point of view on the very title of that work of Aristotle from which Aquinas quotes more freely than from any other. In English it is *On the Soul*; in Latin *De Anima*; but in Greek it is *Περὶ Ψυχῆς*, and *Ψυχῆς* (*psyche*) was in Greek the word for ‘life’ as well as for ‘soul’. Again there is a sinewy quality in Aristotle’s *νουσ ποιητικοσ* and *νουσ παθητικοσ* (*nous poieticus* and *nous patheticus*), which has already faded somewhat from their Latin equivalents *intellectus agens* and *intellectus possibilis*. The *nous* of which Aristotle spoke and thought was clearly less subjective than Aquinas’s *intellectus*; and when he deals with the problem of perception, he polarizes not merely the mind, but the world itself, without explanation or apology, into the two *verbs ποιειν* and *πασχειν* (*poiein* and *paschein*) (‘to do’ and ‘to suffer’). In the psychological and epistemological contexts in which he employs them, these two words alone are as untranslatable as the mentality which they reveal is remote from our own. It is, for instance, not possible to equate them with the Aristotelian ‘matter’ and ‘form’, though matter is certainly passive and form active. For, in the process of perception (he tells us) it is the percept which is active and the perceiving organism which is passive. The organ of perception *is* potentially what the percept already is actually; it ‘suffers’ something unlike itself, but in doing so becomes like what it suffers. The actualization (*ενεργeiα*) of percept and of perception are one and the same thing. When we come to thinking, on the other hand, as distinct from perceiving, while it is the passive mind (*nous patheticus*) which gives us our subjectivity, it is the active mind (*nous poieticus*) which is operative in the act of knowing. The soul is *poiein* to the body’s *paschein*; but soul and body together are (except in the act of knowing) *nous patheticus*. Alike in perceiving and in thinking, there is an active and a passive *movement*, and in both cases the second is the field for the activity of the first. All these complex movements, which are the very stuff of human nature, may be conceived of as potential knowledge; actual knowledge occurs when man becomes wakefully aware of them; for then (*νουσ γιγνεται εκαοτι*² . . . *το δ αντο εστιν η κατ ενεργειαν επστημη τω πραγματι*)³ mind becomes what it thinks and may be said to know itself.

If this kind of psychology was really as tenuous, fine-drawn and obscure—or, to use Bacon’s word, as ‘frigid’—as it seems to most people to-day, it is difficult to explain why, for so many centuries, so many people found it exciting. The true explanation is, once more, that we have lost half the meanings of the key-words in which it is expressed. Above all, with the disappearance of participation, words to do with thinking and perceiving and words to do with movement and space have parted company. Aristotle’s *poiein* and *paschein* were for him, not the insubstantial, semi-mystical abstractions which we make of them, when we translate them as ‘*active principle*’ and ‘*passive principle*’. They were, at the same time, respectively *κινειν* and *κινεισθαι*—’To-move’, and ‘To-be-moved’. Locomotion or traction was for the Greek philosophers only one kind of movement, which included also, change, growth and decay; and the *kinesis*, to which Aristotle refers in so many different contexts, was simply not what we mean by ‘movement’ at all, who think of it as the bare change of position of an idol in Newtonian space.

If we would gain some idea, not only of what ‘movement’ meant before the scientific revolution, but also of that, to us, either foolish or baffling tendency to connect pure thought somehow with space, which we have already observed in the case of Plato’s astronomy, we shall find it more pronounced and explicit in the thought of Plato and his predecessors than in that of Aristotle and his successors. In the *Theaetetus*, for instance, Plato tells us that for Heraclitus and his followers *poiein* and *paschein* (let me now call them *action* and *passion*) were the two primary knids of *kinesis*, and that it is out of them that sense-perception arises. Each of the two was again subdivided into swift and slow. What we call ‘the object’ was slow *action* and what we call the ‘subject’ slow *passion*; while what we call the ‘quality’ of the object was swift *action*, and what we call ‘sensation’, swift *passion*. It is with such images in our minds that we should read Plato himself, when he maintains elsewhere that through perception we share or participate (*κοινωνειν*) in the process of coming into being (*γενεσιξ*). It is with such images in our minds that we should seek to interpret, if we really wish to enter it, the thought of Aristotle and the philosophy and science of the Middle Ages in which so much of that thought lived on.

As to the relation between thought and space, it is almost sufficient to read the *Timaeus*—which, incidentally, was the principal channel through which the thinking of Plato and his predecessors was known to the Middle Ages. In this dialogue, Plato describes the world as a ‘moving image of eternity’. It is however hot simply a matter of a few revealing uses of key-words, though of those there are enough and to spare: as when he tells us that of the sevan different kinds of movement, movement in a circle is *η  περι νουν καυ φρονησιν μαλιοτα ονσα*—’the one that has most to do with mind and understanding’, or again, that by contemplating the undisturbed revolutions (*περιοδοι*) of mind in the heavens we may make use of them for the revolutions of our own intellect, which, though disturbed, are nevertheless akin to the former. It is rather that the whole development and structure of thought in the dialogue is such that celestial astronomy and metaphysics are inextricably one. In the metaphysical discussion of the problem of the one and the many, of identity and difference (which Plato here names *same* and *other*), the abstract notion of sameness is indistinguishable from ‘the Circle of the Same’ (namely the celestial equator), and the abstract notion of difference is indistinguishable from ‘the Circle of the Other’ (namely the Ecliptic, where the planets wander and change).

We have already seen that even in the Middle Ages man’s experience of space was clearly different from our own, and the old tendency to experience as one what we now distinguish absolutely as ‘mind’, on the one hand, and ‘space’ on the other, still finds an echo in the *Divine Comedy*, especially when in the 10th Canto of the *Paradisio* Dante refers to the celestial revolutions as:

>Quanto per mente o per loco si gira.⁴

The impression we get, however, is that it was by then already a good deal nearer to our own than the Greek experience. It is interesting in this connection to observe how Aristotle selects for criticism precisely that astronomical metaphysics to which I have just referred, maintaining that the oneness, or self-identity of *nous* ought not to be conceived spatially (*κατα το μεγεθοξ*) but only numerically, and that accordingly the Circles of which Plato speaks in the *Timaeus* must be ruled out when we are treating of psychology. The proper movement of a circle is revolution; but the proper movement of mind, he insists, is—thinking. This detachment of the idea of thought, first from the idea of movement in space, and then from the idea of movement of any sort, must have been no small feat. It was the beginning of true beta-thinking.

Here we may well pause for a moment to refer back to Harvey’s discovery of the circulation of the blood. It will be remembered from Chapter XII that this was based on the perfection of circular motion and on the formal relation between microcosm and macrocosm. Here then is a striking example of the diminishing experience of participation. First the great circles of the macrocosm are abstracted by Aristotle from the movement of mind and conceived as more purely spatial, and then much later, this very abstraction facilitates a mechanomorphic conception of the movement of the blood. Later still, this conception of the blood plays its part in obliterating from consciousness the whole relation of microcosm to macrocosm on which it was based.

Although aristotle was the pupil of Plato, there are many good reasons for treating the former as beginning a new epoch, the the latter as closing an old one, while not forgetting that all such exact limitations of period have about them something artificial and arbitrary. At some point a thing ceases to be a flower and becomes fruit; but who shall say exactly when? In Raphael’s fresco of the *School of Athens* in the Vatican, the two figures of Plato and Aristotle stand side by side, the one with raised hand pointing upwards to the heavens, the other pointing earthward down a flight of steps. If, in imagination, we take our stand between the two, we can indeed look forward, through the thinking which found expression in Aristotle, to the collective representations of the Western world which were to take their course, through the so-called dark and middle ages, down to the scientific revolution and beyond. While through the other, through the star-and-space-involved thinking of Plato, we may peer backward into the collective representations of the East and of the past. The cosmogony of Plato was still in the Pythagorean stream, and the tradition that Pythagoras visited India, whether in itself it be legendary or historical, is a convenient expression of a process which is apparent from internal evidence. It is many years now since Max M&uuml;ller pointed to a number of coincidences between the philosophy of Plato and the Upanishads, among them the concept of reincarnation, but added that he thought any actual contact unlikely. But if what has been said in this book (particularly Chapter X) is correct, the progress of ideas has been as much, or more, a function of the evolution of consciousness than its vehicle. That is, of consciousness and its correlative, the phenomena or collective representations. Accordingly, that evolution is much less dependent on contacts or communications than has generally been supposed.

When we consider, as is here being attempted, the evolution of consciousness as the progressive decline of participation, the emergence of the Greek from the ancient oriental outlook is a fact which we can contemplate without being unduly troubled by the absence of biographical details about Pythagoras. Anyone who has struggled for a few pages with the Vedas in translation, will know that in their language the entanglement of subject and object, of psychology and natural history, of divine and human, of word and thing, is such as to render the thought virtually unintelligible to a modern reader—though of course he can make some kind of ‘sense’ of it by paraphrazing it into moralizing abstractions of his own. To take only one instance, the word *Namarupa*, or ‘name-form’, takes us back straight away to a stage of consciousness at which that surgical operation, to which I referred in Chapter XII, whereby the thing is separated from its name, had not yet begun to be performed. In the measure that man participates his phenomena, in that measure the name *is* the form, and the form is the name.

At this point, however—that is, with the emergence of Greek thought, so far as it was Platonically inclined, from the hitherto almost wholly religious consciousness of the Orient—I propose to end the movement of this book in the direction of the past and turn its face once more toward the present. To do otherwise would, in the first place, require an acquaintance with oriental languages which I do not possess. But there is another reason. The kind of consciousness which I have hitherto attempted to depict, though characterized by a participation which we lack, is at least, as it were, within sight of our own. We can—or so I have thought—catch glimpses of it which are describable, though with difficulty, in the idol-infected language which the scientific revolution has bequeathed to us. But to depict the kind of consciousness which prevailed at still earlier periods requires, it seems to me, a different method and a different terminology. It may well also demand the extension of historic imagination into a manner of clairvoyance. My purpose is the humbler one of establishing, in the language and imagery of everyday, the bare fact that there has been an evolution of consciousness; and if that is possible at all, it is possible within the limits of Pythagoras and Moses.

>¹ Very shortly, the difficulty about predication out of which logical positivism etc. arose is the following: If I say *a horse is an animal*, then (*a*) if by the word *animal* I mean something more, or less, or other than *horse*, I have told a lie; but (*b*) if I do *not* mean by the word *animal* something more, or less, or other than *horse*, I have said almost nothing. For I might as well have said *a horse is a horse*. Hence the attempts we are now witnessing to replace the traditional logic based on predication by a new logic, in which symbols of algebraic precision refer to ‘atomic’ facts and events having no vestige of connection with the symbols and no hierarchical relation to each other.

>² Aristotle, *De Anima*, Bk. III, Ch. iv.

>³ Ibid., Bk. III, Ch. vii.

>⁴ Whatsoever revolves through mind or space.
