# III<br/>FIGURATION AND THINKING

In the conversion of raindrops into a rainbow, or (if you prefer it) the production of a rainbow out of them, the eye plays a no less indispensable part than the sunlight—or than the drops themselves. In the same way, for the conversion of the unrepresented into a representation, at least one sentient organism is as much a *sine qua non* as the unrepresented itself; and for the conversion of the unrepresented into representations even remotely resembling our everyday world, at least one nervous system organized about a spinal cord culminating in a brain, is equally indispensable. The rainbow analogy does not imply, nor is it intended to suggest, that the solid globe is as insubstantial as a rainbow. The solid globe is solid. The rainbow is not. Only it is important to know what we mean by solidity. More than that, it is necessary to remember what we meant by solidity in one context, when we go on to use the word or think the thing in another.

It is easy to appreciate that there is no such thing as an unseen rainbow. It is not so easy to grasp that there is no such thing as an unheard noise. Or rather it is easy to grasp, but difficult to keep hold of. And this is still more the case, when we come to the sense of tough., Obvious as it may be to reflection that a system of waves or quanta or discrete particles is no more like solid matter than waves of air are like sound, or raindrops like a rainbow, it is not particularly easy to grasp, and it is almost impossible to keep in mind, that there is no such thing as unfelt solidity.¹ It is much more convenient, when we are listening for example to the geologist, to forget what we learnt about matter from the chemist and the physicist. But it really will not do. We cannot go on for ever having it both ways.

It may be expedient at this point to examine a little further the collective representations and our thinking about them. And it is clearly of little use to begin by asking what they are; since they are everything that is obvious. They are, for instance, the desk I am writing at, the noise of a door being opened downstairs, a Union Jack, an altar in a Church, the smell of coffee, a totem pole, the view from Malvern Hills, and the bit of brain-tissue that is being dissected before a group of students in a hospital laboratory. Some of them we can manipulate, as the lecturer is doing, and as I do when I move the desk. Some of them we cannot. What is important here is that there are, broadly speaking, three different things that we can do with all of them; or alternatively, they are related to the mind in three different ways.

First, we can simply contemplate or experience them—as when I simply look at the view, or encounter the smell. The whole impression appears then to be given to me in the representation itself. For I am not, or I am not very often, aware of smelling an unidentified smell and then thinking, ‘That is coffee!’ It appears to me, and appears instantly, that I smell coffee—though, in face, I can no more merely *smell* ‘coffee’ than I can merely *hear* ‘a thrush singing’. This immediate impression or experience of a familiar world has already been mentioned in Chapter II. It is important to be clear about it. It is plainly the result of an activity of some sort in me, however little I may recollect any such activity.

When a lady complained to Whistler that she did not see the world he painted, he is said to have replied: ‘No, ma’am, but don’t you wish you could?’ Both Whistler and the lady were really referring to that activity—which in Whistler’s case was intenser than the lady’s. Ought it to be called a ‘mental’ activity? Whatever it ought to be called, it really is the percipient’s own contribution to the representation. It is all *that* in the representation that is not sensation. For, as the organs of sense are required to convert the unrepresented (‘particles’) into sensations for us, so *something* is required in us to convert sensations into ‘things’. It is this something that I mean. And it will avoid confusion if I purposely choose an unfamiliar and little-used word and call it, at the risk of infelicity, *figuration*.

Now whether or no figuration is a mental activity, that is, a kind of thinking, it is clearly not, or it is not *characteristically*, a thinking *about*. The second thing, therefore, that we can do with the representations is to think about them. Here, as before, we remain unconscious of the intimate relation which they have, as representations, with our own organisms and minds. Or rather, more unconscious than before. For now our very attitude is, to treat them as independent of ourselves; to accept their ‘outness’ as self-evidently given; and to speculate about or to investigate their relations *with each other*. One could perhaps name this process ‘theorizing’ or ‘theoretical thinking’, since it is exactly what is done in most places where science is pursued, whether it be botany, medicine, metallurgy, zoology or any other. But I do not think the term is wide enough. The kind of thing I mean covers other studies as well—a good deal of history, for instance. Nor need it be systematic. There are very few children who do not do a little of it. Moreover, if a common word is chosen, there is the same danger of confusion arising from its occasional use with a less precise intention. Therefore, at the like hazard as before, I propose to call this particular kind of thinking *alpha-thinking*.

Thirdly, we can think about the *nature* of collective representations as such, and therefore about their relation to our own minds. We can think about perceiving and we can think about thinking. We can do, in fact, the kind of thinking which I am trying to do at the moment, and which you will be doing if you think I am right and also if you think I am wrong. This is part of the province of one or two sciences such as physiology and psychology, and of course it is also part of the province of philosophy. It has been called reflection or reflective thinking. But for the same reasons as before, I shall reject the simpler and more elegant term and call it *beta-thinking*.

It should be particularly noted that the distinction here made between alpha-thinking and beta-thinking is not one between two different *kinds* of thinking, such as for instance that which is sometimes made between analytical thinking on the one hand and synthetic or imaginative thinking on the other. It is purely a distinction of subject-matters.

The three operations—*figuration*, *alpha-thinking* and *beta-thinking*—are clearly distinguishable from one another; but that is not to say that they are divided by impassable barriers at the points where they mutually approach. Indeed the reverse is true. Moreover they may affect each other by reciprocal influence. In the history of the theory of colour, for instance, colour began by being regarded as a primary quality of the coloured object and was later transferred to the status of a ‘secondary’ quality dependent on the beholder. Here we can detect the interaction of alpha-thinking and beta-thinking; and again in the whole influence which experimental science has exerted on philosophy in the last two or three hundred years. This book, on the other hand, will be more concerned with the interaction between figuration and alpha-thinking.

That the former of these affects, and largely determines, the latter hardly needs saying; since the primary product of figuration is the actual subject-matter of most alpha-thinking. That the converse may sometimes also be true,k and further, that the borderline between the one and the other is sometimes quite impossible to determine—this is less obvious. Yet a little serious reflection (that is, a little beta-thinking) makes it apparent enough.

Recall for a moment the familiar jingle from *Sylvie and Bruno*, with its persistent refrain of ‘he thought he saw’ followed by ‘he found it was’:

>*He thought he saw a Banker’s Clerk<br/>Descending from the bus,<br/>He looked again and found it was<br/>A hippopotamus.<br/>etc., etc.*

This is of course only a very improbable instance of an experience which, in itself, is quite common, especially with those among our representation (and they form the overwhelming majority) which reach us through the sense of sight alone. When we mistake one representation, that is to say one thing, for another, so that there is a transition from an ‘I thought I saw’ to an ‘I found it was’, it is often very difficult indeed to say whether there is first a figuration (based, let us say, on incomplete sensation) and then another and different figuration, producing a different representation; or whether there is one and the same representation veiled from us at first by some incorrect afpha-thinking which is subsequently discarded as inapplicable. In the particular case of a puzzled man trying to descry an object spotted far off at sea, it feels more like the latter. Often it feels much more like the former. We have made the mistake before we are aware of having done any thinking at all.

Anyone who wishes to investigate this further should attend carefully to the sort of mistakes we are apt to make on awaking abruptly from deep sleep in a darkened room; expecially if it happens to be a strange room. Either way we must conclude that figuration, whether or no it is a kind of thinking, is something which easily and imperceptibly passes over into thinking, and into which thinking easily and imperceptibly passes over. For in both cases there was a representation; otherwise I should not have been deceived. And if the first representation was the result of incorrect thinking, then thinking can do something very much like what figuration does. Alternatively, if it was the result of figuration alone, then the very fact of that figuration can ‘make a mistake’ suggests that it has a good deal in common with thinking.

>¹’The thermometer is below freezing point, the pipe is cracked, and no water comes out of the tap. I know nothing about physics or chemistry; but surely I can say that there is solid ice in the pipe!’ Certainly you can; and if there was salt in the water, you can say that there is solid, *white* ice in the pipe. I am only pointing out that the solidity you are talking about involves your fancied touch, just as the whiteness involves your fancied glance. Only it is harder to remember.
